// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_message`

/// 全部保存的连接。没有配置文件时返回空列表，不报错
Future<List<SavedConnection>> listConnections() =>
    RustLib.instance.api.crateApiConnectionsListConnections();

/// 新增或更新。password 为 None 表示保留钥匙串里已有的那份
Future<void> saveConnection({
  required SavedConnection connection,
  String? password,
}) => RustLib.instance.api.crateApiConnectionsSaveConnection(
  connection: connection,
  password: password,
);

/// 删连接，钥匙串里的密码一并清掉
Future<void> deleteConnection({required String id}) =>
    RustLib.instance.api.crateApiConnectionsDeleteConnection(id: id);

/// 从钥匙串取密码。没存过返回 null，界面据此提示用户输一次
Future<String?> loadPassword({required String id}) =>
    RustLib.instance.api.crateApiConnectionsLoadPassword(id: id);

class SavedConnection {
  final String id;
  final String name;
  final String host;
  final int port;
  final String user;
  final String? database;

  const SavedConnection({
    required this.id,
    required this.name,
    required this.host,
    required this.port,
    required this.user,
    this.database,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      database.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SavedConnection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          database == other.database;
}
