// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'value.dart';
part 'csv_import.freezed.dart';

/// 读前 limit 行预览。有表头时表头不算在 limit 里
Future<CsvPreview> previewCsv({
  required String path,
  required ImportOptions options,
  required BigInt limit,
}) => RustLib.instance.api.crateApiCsvImportPreviewCsv(
  path: path,
  options: options,
  limit: limit,
);

/// 按表头建议一个映射：下标是 CSV 列，值是目标列下标，null 表示跳过
List<int?> suggestMapping({
  required List<String> header,
  required List<TargetColumn> columns,
}) => RustLib.instance.api.crateApiCsvImportSuggestMapping(
  header: header,
  columns: columns,
);

/// 目标表的列（能不能写、要不要必填）和当前 sql_mode
Future<ImportTarget> prepareImport({
  required BigInt sessionId,
  required String database,
  required String table,
}) => RustLib.instance.api.crateApiCsvImportPrepareImport(
  sessionId: sessionId,
  database: database,
  table: table,
);

/// 在后台开始导入，返回任务 id。映射不对、文件打不开当场报错
Future<BigInt> startImport({
  required BigInt sessionId,
  required ImportRequest request,
}) => RustLib.instance.api.crateApiCsvImportStartImport(
  sessionId: sessionId,
  request: request,
);

/// 进度，结束后是报告。界面轮询
Future<ImportStatus> importStatus({required BigInt jobId}) =>
    RustLib.instance.api.crateApiCsvImportImportStatus(jobId: jobId);

Future<void> cancelImport({required BigInt jobId}) =>
    RustLib.instance.api.crateApiCsvImportCancelImport(jobId: jobId);

/// 失败的行另存成 CSV，返回行数
Future<BigInt> saveImportErrors({
  required BigInt jobId,
  required String path,
}) => RustLib.instance.api.crateApiCsvImportSaveImportErrors(
  jobId: jobId,
  path: path,
);

/// 关掉任务并删掉错误行临时文件。对话框关闭时必须调
Future<void> closeImport({required BigInt jobId}) =>
    RustLib.instance.api.crateApiCsvImportCloseImport(jobId: jobId);

class CsvPreview {
  final List<String> header;
  final BigInt columnCount;
  final List<PreviewRow> rows;
  final String? error;

  const CsvPreview({
    required this.header,
    required this.columnCount,
    required this.rows,
    this.error,
  });

  @override
  int get hashCode =>
      header.hashCode ^ columnCount.hashCode ^ rows.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CsvPreview &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          columnCount == other.columnCount &&
          rows == other.rows &&
          error == other.error;
}

class ImportOptions {
  final ExportEncoding encoding;
  final String delimiter;
  final bool header;
  final String nullText;

  const ImportOptions({
    required this.encoding,
    required this.delimiter,
    required this.header,
    required this.nullText,
  });

  @override
  int get hashCode =>
      encoding.hashCode ^
      delimiter.hashCode ^
      header.hashCode ^
      nullText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportOptions &&
          runtimeType == other.runtimeType &&
          encoding == other.encoding &&
          delimiter == other.delimiter &&
          header == other.header &&
          nullText == other.nullText;
}

@freezed
sealed class ImportOutcome with _$ImportOutcome {
  const ImportOutcome._();

  const factory ImportOutcome.completed() = ImportOutcome_Completed;
  const factory ImportOutcome.rolledBack() = ImportOutcome_RolledBack;
  const factory ImportOutcome.stopped(String field0) = ImportOutcome_Stopped;
}

class ImportProgress {
  final BigInt bytesRead;
  final BigInt totalBytes;
  final BigInt rowsRead;
  final BigInt rowsInserted;
  final BigInt rowsFailed;

  const ImportProgress({
    required this.bytesRead,
    required this.totalBytes,
    required this.rowsRead,
    required this.rowsInserted,
    required this.rowsFailed,
  });

  @override
  int get hashCode =>
      bytesRead.hashCode ^
      totalBytes.hashCode ^
      rowsRead.hashCode ^
      rowsInserted.hashCode ^
      rowsFailed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportProgress &&
          runtimeType == other.runtimeType &&
          bytesRead == other.bytesRead &&
          totalBytes == other.totalBytes &&
          rowsRead == other.rowsRead &&
          rowsInserted == other.rowsInserted &&
          rowsFailed == other.rowsFailed;
}

class ImportReport {
  final ImportProgress progress;
  final ImportOutcome outcome;
  final List<RowError> errors;

  const ImportReport({
    required this.progress,
    required this.outcome,
    required this.errors,
  });

  @override
  int get hashCode => progress.hashCode ^ outcome.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportReport &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          outcome == other.outcome &&
          errors == other.errors;
}

class ImportRequest {
  final String path;
  final ImportOptions options;
  final String schema;
  final String table;
  final List<int?> mapping;
  final int batchRows;
  final OnError onError;

  const ImportRequest({
    required this.path,
    required this.options,
    required this.schema,
    required this.table,
    required this.mapping,
    required this.batchRows,
    required this.onError,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      options.hashCode ^
      schema.hashCode ^
      table.hashCode ^
      mapping.hashCode ^
      batchRows.hashCode ^
      onError.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportRequest &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          options == other.options &&
          schema == other.schema &&
          table == other.table &&
          mapping == other.mapping &&
          batchRows == other.batchRows &&
          onError == other.onError;
}

@freezed
sealed class ImportStatus with _$ImportStatus {
  const ImportStatus._();

  const factory ImportStatus.running(ImportProgress field0) =
      ImportStatus_Running;
  const factory ImportStatus.finished(ImportReport field0) =
      ImportStatus_Finished;
}

class ImportTarget {
  final String schema;
  final String table;
  final List<TargetColumn> columns;
  final String sqlMode;
  final bool strict;

  const ImportTarget({
    required this.schema,
    required this.table,
    required this.columns,
    required this.sqlMode,
    required this.strict,
  });

  @override
  int get hashCode =>
      schema.hashCode ^
      table.hashCode ^
      columns.hashCode ^
      sqlMode.hashCode ^
      strict.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImportTarget &&
          runtimeType == other.runtimeType &&
          schema == other.schema &&
          table == other.table &&
          columns == other.columns &&
          sqlMode == other.sqlMode &&
          strict == other.strict;
}

enum OnError { rollbackAll, skipRow }

class PreviewRow {
  final BigInt line;
  final List<DisplayCell> cells;
  final String? error;

  const PreviewRow({required this.line, required this.cells, this.error});

  @override
  int get hashCode => line.hashCode ^ cells.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreviewRow &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          cells == other.cells &&
          error == other.error;
}

class RowError {
  final BigInt line;
  final String reason;

  const RowError({required this.line, required this.reason});

  @override
  int get hashCode => line.hashCode ^ reason.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RowError &&
          runtimeType == other.runtimeType &&
          line == other.line &&
          reason == other.reason;
}

class TargetColumn {
  final String name;
  final String columnType;
  final bool nullable;
  final bool autoIncrement;
  final bool isBinary;
  final bool generated;
  final bool mandatory;

  const TargetColumn({
    required this.name,
    required this.columnType,
    required this.nullable,
    required this.autoIncrement,
    required this.isBinary,
    required this.generated,
    required this.mandatory,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      columnType.hashCode ^
      nullable.hashCode ^
      autoIncrement.hashCode ^
      isBinary.hashCode ^
      generated.hashCode ^
      mandatory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TargetColumn &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          columnType == other.columnType &&
          nullable == other.nullable &&
          autoIncrement == other.autoIncrement &&
          isBinary == other.isBinary &&
          generated == other.generated &&
          mandatory == other.mandatory;
}
