// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'value.dart';
part 'db.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `on_runtime`, `runtime`, `to_message`

/// 开会话，返回会话 id。此时还没有真正连上，第一次查询才建立 TCP 连接
Future<BigInt> openSession({required ConnectionConfig config}) =>
    RustLib.instance.api.crateApiDbOpenSession(config: config);

/// 跑查询，结果留在 Rust 侧，只回概况
Future<QuerySummary> execute({
  required BigInt sessionId,
  required String sql,
  required BigInt maxRows,
}) => RustLib.instance.api.crateApiDbExecute(
  sessionId: sessionId,
  sql: sql,
  maxRows: maxRows,
);

/// 取可视区的显示文本，网格渲染走这条。整个结果集不跨 FFI，界面滚到哪取到哪
Future<List<List<String>>> fetchWindowText({
  required BigInt sessionId,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiDbFetchWindowText(
  sessionId: sessionId,
  offset: offset,
  limit: limit,
);

/// 取可视区的原始值，编辑单元格时走这条
Future<List<List<CellValue>>> fetchWindow({
  required BigInt sessionId,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiDbFetchWindow(
  sessionId: sessionId,
  offset: offset,
  limit: limit,
);

/// 改一个单元格并写回。不可编辑、定位不到行、影响行数不为 1 都会报错
Future<void> applyEdit({
  required BigInt sessionId,
  required BigInt rowIndex,
  required BigInt columnIndex,
  required CellValue newValue,
}) => RustLib.instance.api.crateApiDbApplyEdit(
  sessionId: sessionId,
  rowIndex: rowIndex,
  columnIndex: columnIndex,
  newValue: newValue,
);

/// 插一行，返回新的总行数。values[i] 为 null 表示这一列交给 DEFAULT / 自增
Future<BigInt> insertRow({
  required BigInt sessionId,
  required List<CellValue?> values,
}) => RustLib.instance.api.crateApiDbInsertRow(
  sessionId: sessionId,
  values: values,
);

/// 在一个事务里删若干行，返回新的总行数。任何一行没删成就整体回滚
Future<BigInt> deleteRows({
  required BigInt sessionId,
  required Uint64List rowIndexes,
}) => RustLib.instance.api.crateApiDbDeleteRows(
  sessionId: sessionId,
  rowIndexes: rowIndexes,
);

/// 把一片单元格编码成 TSV，列按 column_indexes 的顺序。选区不用在界面窗口里
Future<String> copyRange({
  required BigInt sessionId,
  required BigInt rowStart,
  required BigInt rowCount,
  required Uint64List columnIndexes,
}) => RustLib.instance.api.crateApiDbCopyRange(
  sessionId: sessionId,
  rowStart: rowStart,
  rowCount: rowCount,
  columnIndexes: columnIndexes,
);

/// 解析剪贴板里的 TSV。不带引号的 NULL 是 NULL，其余都是文本；不是规整矩形就报错
Future<List<List<CellValue>>> parseClipboard({required String text}) =>
    RustLib.instance.api.crateApiDbParseClipboard(text: text);

/// 从 row_start 起把一块值粘进这几列，返回写了多少格。一个事务，任何一格失败整体回滚
Future<BigInt> pasteCells({
  required BigInt sessionId,
  required BigInt rowStart,
  required Uint64List columnIndexes,
  required List<List<CellValue>> values,
}) => RustLib.instance.api.crateApiDbPasteCells(
  sessionId: sessionId,
  rowStart: rowStart,
  columnIndexes: columnIndexes,
  values: values,
);

/// 关会话并断开连接池
Future<void> closeSession({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDbCloseSession(sessionId: sessionId);

class ColumnMeta {
  final String name;
  final String orgName;
  final String orgTable;
  final String schema;
  final bool isBinary;

  const ColumnMeta({
    required this.name,
    required this.orgName,
    required this.orgTable,
    required this.schema,
    required this.isBinary,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      orgName.hashCode ^
      orgTable.hashCode ^
      schema.hashCode ^
      isBinary.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          orgName == other.orgName &&
          orgTable == other.orgTable &&
          schema == other.schema &&
          isBinary == other.isBinary;
}

class ConnectionConfig {
  final String host;
  final int port;
  final String user;
  final String password;
  final String? database;

  const ConnectionConfig({
    required this.host,
    required this.port,
    required this.user,
    required this.password,
    this.database,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      password.hashCode ^
      database.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          password == other.password &&
          database == other.database;
}

class EditTarget {
  final String schema;
  final String table;
  final Uint64List keyIndexes;

  const EditTarget({
    required this.schema,
    required this.table,
    required this.keyIndexes,
  });

  @override
  int get hashCode => schema.hashCode ^ table.hashCode ^ keyIndexes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditTarget &&
          runtimeType == other.runtimeType &&
          schema == other.schema &&
          table == other.table &&
          keyIndexes == other.keyIndexes;
}

@freezed
sealed class Editability with _$Editability {
  const Editability._();

  const factory Editability.editable(EditTarget field0) = Editability_Editable;
  const factory Editability.readOnly(String field0) = Editability_ReadOnly;
}

class QuerySummary {
  final List<ColumnMeta> columns;
  final BigInt totalRows;
  final bool truncated;
  final Editability editability;
  final String? layoutKey;

  const QuerySummary({
    required this.columns,
    required this.totalRows,
    required this.truncated,
    required this.editability,
    this.layoutKey,
  });

  @override
  int get hashCode =>
      columns.hashCode ^
      totalRows.hashCode ^
      truncated.hashCode ^
      editability.hashCode ^
      layoutKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuerySummary &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          totalRows == other.totalRows &&
          truncated == other.truncated &&
          editability == other.editability &&
          layoutKey == other.layoutKey;
}
