// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'options.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import 'value.dart';
part 'db.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `on_runtime`, `runtime`, `to_message`

/// 开会话，返回会话 id。直连时还没有真正连上，第一次查询才建立 TCP 连接；
/// 走 SSH 时当场建隧道，未知主机、密钥不符、认证失败在这里就报出来
Future<BigInt> openSession({required ConnectionConfig config}) =>
    RustLib.instance.api.crateApiDbOpenSession(config: config);

/// 跑查询，结果留在 Rust 侧，只回概况
Future<QuerySummary> execute({
  required BigInt sessionId,
  required String sql,
  required BigInt maxRows,
}) => RustLib.instance.api.crateApiDbExecute(
  sessionId: sessionId,
  sql: sql,
  maxRows: maxRows,
);

/// 在原查询上套分组筛选（可嵌套、带 IN / NOT IN）和排序再跑。SQL 在 core 里生成，值走参数化。
/// 空分组、sort_column 为 null 时就是原样跑 sql
Future<QuerySummary> executeFilteredView({
  required BigInt sessionId,
  required String sql,
  required FilterGroup filter,
  String? sortColumn,
  required bool sortAscending,
  required BigInt maxRows,
}) => RustLib.instance.api.crateApiDbExecuteFilteredView(
  sessionId: sessionId,
  sql: sql,
  filter: filter,
  sortColumn: sortColumn,
  sortAscending: sortAscending,
  maxRows: maxRows,
);

/// 取可视区的显示文本，网格渲染走这条。整个结果集不跨 FFI，界面滚到哪取到哪
Future<List<List<DisplayCell>>> fetchWindowText({
  required BigInt sessionId,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiDbFetchWindowText(
  sessionId: sessionId,
  offset: offset,
  limit: limit,
);

/// 取可视区的原始值，编辑单元格时走这条
Future<List<List<CellValue>>> fetchWindow({
  required BigInt sessionId,
  required BigInt offset,
  required BigInt limit,
}) => RustLib.instance.api.crateApiDbFetchWindow(
  sessionId: sessionId,
  offset: offset,
  limit: limit,
);

/// 改一个单元格并写回。不可编辑、定位不到行、影响行数不为 1 都会报错
Future<void> applyEdit({
  required BigInt sessionId,
  required BigInt rowIndex,
  required BigInt columnIndex,
  required CellValue newValue,
}) => RustLib.instance.api.crateApiDbApplyEdit(
  sessionId: sessionId,
  rowIndex: rowIndex,
  columnIndex: columnIndex,
  newValue: newValue,
);

/// 按主键从库里重读一行放回缓存。库里找不到这一行就报错，缓存不动
Future<void> refreshRow({
  required BigInt sessionId,
  required BigInt rowIndex,
}) => RustLib.instance.api.crateApiDbRefreshRow(
  sessionId: sessionId,
  rowIndex: rowIndex,
);

/// 插一行，返回新的总行数。values[i] 为 null 表示这一列交给 DEFAULT / 自增
Future<BigInt> insertRow({
  required BigInt sessionId,
  required List<CellValue?> values,
}) => RustLib.instance.api.crateApiDbInsertRow(
  sessionId: sessionId,
  values: values,
);

/// 在一个事务里删若干行，返回新的总行数。任何一行没删成就整体回滚
Future<BigInt> deleteRows({
  required BigInt sessionId,
  required Uint64List rowIndexes,
}) => RustLib.instance.api.crateApiDbDeleteRows(
  sessionId: sessionId,
  rowIndexes: rowIndexes,
);

/// 把一片单元格编码成 TSV，列按 column_indexes 的顺序。选区不用在界面窗口里
Future<String> copyRange({
  required BigInt sessionId,
  required BigInt rowStart,
  required BigInt rowCount,
  required Uint64List columnIndexes,
}) => RustLib.instance.api.crateApiDbCopyRange(
  sessionId: sessionId,
  rowStart: rowStart,
  rowCount: rowCount,
  columnIndexes: columnIndexes,
);

/// 解析剪贴板里的 TSV。不带引号的 NULL 是 NULL，其余都是文本；不是规整矩形就报错
Future<List<List<CellValue>>> parseClipboard({required String text}) =>
    RustLib.instance.api.crateApiDbParseClipboard(text: text);

/// 从 row_start 起把一块值粘进这几列，返回写了多少格。一个事务，任何一格失败整体回滚
Future<BigInt> pasteCells({
  required BigInt sessionId,
  required BigInt rowStart,
  required Uint64List columnIndexes,
  required List<List<CellValue>> values,
}) => RustLib.instance.api.crateApiDbPasteCells(
  sessionId: sessionId,
  rowStart: rowStart,
  columnIndexes: columnIndexes,
  values: values,
);

/// 结果集某一列的 ENUM / SET 可选值，按定义顺序
Future<List<String>> columnChoices({
  required BigInt sessionId,
  required BigInt columnIndex,
}) => RustLib.instance.api.crateApiDbColumnChoices(
  sessionId: sessionId,
  columnIndex: columnIndex,
);

/// 把结果集的一段写成文件，row_count 为 null 表示到末尾。行不经过 FFI
Future<ExportSummary> exportRows({
  required BigInt sessionId,
  required String path,
  required BigInt rowStart,
  BigInt? rowCount,
  required Uint64List columnIndexes,
  required ExportOptions options,
}) => RustLib.instance.api.crateApiDbExportRows(
  sessionId: sessionId,
  path: path,
  rowStart: rowStart,
  rowCount: rowCount,
  columnIndexes: columnIndexes,
  options: options,
);

/// 关会话并断开连接池
Future<void> closeSession({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiDbCloseSession(sessionId: sessionId);

enum ColumnKind {
  text,
  number,
  json,
  date,
  dateTime,
  time,
  enum_,
  set_,
  binary,
}

class ColumnMeta {
  final String name;
  final String orgName;
  final String orgTable;
  final String schema;
  final bool isBinary;
  final ColumnKind kind;
  final int decimals;

  const ColumnMeta({
    required this.name,
    required this.orgName,
    required this.orgTable,
    required this.schema,
    required this.isBinary,
    required this.kind,
    required this.decimals,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      orgName.hashCode ^
      orgTable.hashCode ^
      schema.hashCode ^
      isBinary.hashCode ^
      kind.hashCode ^
      decimals.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          orgName == other.orgName &&
          orgTable == other.orgTable &&
          schema == other.schema &&
          isBinary == other.isBinary &&
          kind == other.kind &&
          decimals == other.decimals;
}

class ConnectionConfig {
  final String host;
  final int port;
  final String user;
  final String password;
  final String? database;
  final ConnectionOptions options;
  final List<String?> sshSecrets;
  final String? savedId;

  const ConnectionConfig({
    required this.host,
    required this.port,
    required this.user,
    required this.password,
    this.database,
    required this.options,
    required this.sshSecrets,
    this.savedId,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      user.hashCode ^
      password.hashCode ^
      database.hashCode ^
      options.hashCode ^
      sshSecrets.hashCode ^
      savedId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          password == other.password &&
          database == other.database &&
          options == other.options &&
          sshSecrets == other.sshSecrets &&
          savedId == other.savedId;
}

class EditTarget {
  final String schema;
  final String table;
  final Uint64List keyIndexes;

  const EditTarget({
    required this.schema,
    required this.table,
    required this.keyIndexes,
  });

  @override
  int get hashCode => schema.hashCode ^ table.hashCode ^ keyIndexes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EditTarget &&
          runtimeType == other.runtimeType &&
          schema == other.schema &&
          table == other.table &&
          keyIndexes == other.keyIndexes;
}

@freezed
sealed class Editability with _$Editability {
  const Editability._();

  const factory Editability.editable(EditTarget field0) = Editability_Editable;
  const factory Editability.readOnly(String field0) = Editability_ReadOnly;
}

enum ExportEncoding { utf8, utf8Bom, gbk }

enum ExportFormat { csv, sqlInsert }

class ExportOptions {
  final ExportFormat format;
  final ExportEncoding encoding;
  final String delimiter;
  final bool header;
  final String nullText;
  final String tableName;

  const ExportOptions({
    required this.format,
    required this.encoding,
    required this.delimiter,
    required this.header,
    required this.nullText,
    required this.tableName,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      encoding.hashCode ^
      delimiter.hashCode ^
      header.hashCode ^
      nullText.hashCode ^
      tableName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportOptions &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          encoding == other.encoding &&
          delimiter == other.delimiter &&
          header == other.header &&
          nullText == other.nullText &&
          tableName == other.tableName;
}

class ExportSummary {
  final BigInt rowsWritten;
  final bool sourceTruncated;

  const ExportSummary({
    required this.rowsWritten,
    required this.sourceTruncated,
  });

  @override
  int get hashCode => rowsWritten.hashCode ^ sourceTruncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSummary &&
          runtimeType == other.runtimeType &&
          rowsWritten == other.rowsWritten &&
          sourceTruncated == other.sourceTruncated;
}

class FilterCondition {
  final String column;
  final FilterOp op;
  final String value;

  const FilterCondition({
    required this.column,
    required this.op,
    required this.value,
  });

  @override
  int get hashCode => column.hashCode ^ op.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterCondition &&
          runtimeType == other.runtimeType &&
          column == other.column &&
          op == other.op &&
          value == other.value;
}

class FilterGroup {
  final bool matchAll;
  final List<FilterItem> items;

  const FilterGroup({required this.matchAll, required this.items});

  @override
  int get hashCode => matchAll.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FilterGroup &&
          runtimeType == other.runtimeType &&
          matchAll == other.matchAll &&
          items == other.items;
}

@freezed
sealed class FilterItem with _$FilterItem {
  const FilterItem._();

  const factory FilterItem.condition(FilterCondition field0) =
      FilterItem_Condition;
  const factory FilterItem.group(FilterGroup field0) = FilterItem_Group;
}

enum FilterOp {
  eq,
  notEq,
  lt,
  ltEq,
  gt,
  gtEq,
  contains,
  notContains,
  startsWith,
  endsWith,
  isNull,
  isNotNull,
  in_,
  notIn,
}

/// 开会话失败。主机密钥没通过校验时带着 host_key，界面据此问用户要不要信任；
/// 其余情况只有 message
class OpenSessionError implements FrbException {
  final String message;
  final HostKeyIssue? hostKey;

  const OpenSessionError({required this.message, this.hostKey});

  @override
  String toString() => message;

  @override
  int get hashCode => message.hashCode ^ hostKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OpenSessionError &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          hostKey == other.hostKey;
}

class QuerySummary {
  final List<ColumnMeta> columns;
  final BigInt totalRows;
  final bool truncated;
  final Editability editability;
  final String? layoutKey;

  const QuerySummary({
    required this.columns,
    required this.totalRows,
    required this.truncated,
    required this.editability,
    this.layoutKey,
  });

  @override
  int get hashCode =>
      columns.hashCode ^
      totalRows.hashCode ^
      truncated.hashCode ^
      editability.hashCode ^
      layoutKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QuerySummary &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          totalRows == other.totalRows &&
          truncated == other.truncated &&
          editability == other.editability &&
          layoutKey == other.layoutKey;
}
