// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'db.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 读一个库的表和列缓存在会话里，给补全用。返回表的数量
Future<BigInt> loadCatalog({
  required BigInt sessionId,
  required String database,
}) => RustLib.instance.api.crateApiEditorLoadCatalog(
  sessionId: sessionId,
  database: database,
);

/// 补全。纯计算读缓存的目录，敲键时调，所以是同步调用。位置都是 UTF-16 下标
Completion completeSql({
  required BigInt sessionId,
  required String sql,
  required int cursor,
}) => RustLib.instance.api.crateApiEditorCompleteSql(
  sessionId: sessionId,
  sql: sql,
  cursor: cursor,
);

/// 切 token，位置是 UTF-16 下标。编辑器每次重绘都调，所以是同步调用
List<SqlToken> tokenizeSql({required String sql}) =>
    RustLib.instance.api.crateApiEditorTokenizeSql(sql: sql);

/// 执行过的 SQL，最新的在前
Future<List<HistoryEntry>> listHistory() =>
    RustLib.instance.api.crateApiEditorListHistory();

Future<void> addHistory({required String sql}) =>
    RustLib.instance.api.crateApiEditorAddHistory(sql: sql);

Future<List<Favorite>> listFavorites() =>
    RustLib.instance.api.crateApiEditorListFavorites();

/// 收藏，同名覆盖，返回 id
Future<String> saveFavorite({required String name, required String sql}) =>
    RustLib.instance.api.crateApiEditorSaveFavorite(name: name, sql: sql);

Future<void> deleteFavorite({required String id}) =>
    RustLib.instance.api.crateApiEditorDeleteFavorite(id: id);

/// 编辑器里有几条语句。界面据此决定走单条（能筛选排序）还是多条脚本
List<String> splitStatements({required String sql}) =>
    RustLib.instance.api.crateApiEditorSplitStatements(sql: sql);

/// 多条语句按顺序在同一条连接上跑，每个结果集一个子会话
Future<ScriptSummary> executeScript({
  required BigInt sessionId,
  required String sql,
  required BigInt maxRows,
}) => RustLib.instance.api.crateApiEditorExecuteScript(
  sessionId: sessionId,
  sql: sql,
  maxRows: maxRows,
);

/// 执行计划，结果放进一个子会话
Future<StatementOutcome> explain({
  required BigInt sessionId,
  required String sql,
  required BigInt maxRows,
}) => RustLib.instance.api.crateApiEditorExplain(
  sessionId: sessionId,
  sql: sql,
  maxRows: maxRows,
);

/// 新一轮运行前关掉上一轮的子结果
Future<void> dropChildResults({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiEditorDropChildResults(sessionId: sessionId);

class Completion {
  final int replaceStart;
  final int replaceEnd;
  final List<CompletionItem> items;

  const Completion({
    required this.replaceStart,
    required this.replaceEnd,
    required this.items,
  });

  @override
  int get hashCode =>
      replaceStart.hashCode ^ replaceEnd.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Completion &&
          runtimeType == other.runtimeType &&
          replaceStart == other.replaceStart &&
          replaceEnd == other.replaceEnd &&
          items == other.items;
}

class CompletionItem {
  final String label;
  final String insertText;
  final CompletionKind kind;
  final String detail;

  const CompletionItem({
    required this.label,
    required this.insertText,
    required this.kind,
    required this.detail,
  });

  @override
  int get hashCode =>
      label.hashCode ^ insertText.hashCode ^ kind.hashCode ^ detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompletionItem &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          insertText == other.insertText &&
          kind == other.kind &&
          detail == other.detail;
}

enum CompletionKind { table, column, alias, keyword }

class Favorite {
  final String id;
  final String name;
  final String sql;

  const Favorite({required this.id, required this.name, required this.sql});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ sql.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Favorite &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          sql == other.sql;
}

class HistoryEntry {
  final String sql;
  final PlatformInt64 executedAt;

  const HistoryEntry({required this.sql, required this.executedAt});

  @override
  int get hashCode => sql.hashCode ^ executedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryEntry &&
          runtimeType == other.runtimeType &&
          sql == other.sql &&
          executedAt == other.executedAt;
}

class ScriptSummary {
  final List<StatementOutcome> outcomes;
  final StatementFailure? failure;

  const ScriptSummary({required this.outcomes, this.failure});

  @override
  int get hashCode => outcomes.hashCode ^ failure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScriptSummary &&
          runtimeType == other.runtimeType &&
          outcomes == other.outcomes &&
          failure == other.failure;
}

class SqlToken {
  final SqlTokenKind kind;
  final int start;
  final int end;

  const SqlToken({required this.kind, required this.start, required this.end});

  @override
  int get hashCode => kind.hashCode ^ start.hashCode ^ end.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SqlToken &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          start == other.start &&
          end == other.end;
}

enum SqlTokenKind {
  keyword,
  identifier,
  quotedIdentifier,
  string,
  number,
  comment,
  variable,
  operator_,
  punctuation,
}

class StatementFailure {
  final int index;
  final String sql;
  final String message;

  const StatementFailure({
    required this.index,
    required this.sql,
    required this.message,
  });

  @override
  int get hashCode => index.hashCode ^ sql.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementFailure &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          sql == other.sql &&
          message == other.message;
}

class StatementOutcome {
  final String sql;
  final BigInt? sessionId;
  final QuerySummary? summary;
  final BigInt affectedRows;

  const StatementOutcome({
    required this.sql,
    this.sessionId,
    this.summary,
    required this.affectedRows,
  });

  @override
  int get hashCode =>
      sql.hashCode ^
      sessionId.hashCode ^
      summary.hashCode ^
      affectedRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatementOutcome &&
          runtimeType == other.runtimeType &&
          sql == other.sql &&
          sessionId == other.sessionId &&
          summary == other.summary &&
          affectedRows == other.affectedRows;
}
