// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 某张表记住的布局，没记过是空列表
Future<List<ColumnLayout>> loadLayout({required String key}) =>
    RustLib.instance.api.crateApiLayoutsLoadLayout(key: key);

/// 记住布局。这次没出现的列保留上次的宽度
Future<void> saveLayout({
  required String key,
  required List<ColumnLayout> columns,
}) =>
    RustLib.instance.api.crateApiLayoutsSaveLayout(key: key, columns: columns);

class ColumnLayout {
  final String name;
  final double width;

  const ColumnLayout({required this.name, required this.width});

  @override
  int get hashCode => name.hashCode ^ width.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnLayout &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          width == other.width;
}
