// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'options.freezed.dart';

/// 默认选项。界面新建连接时用它，不在 Dart 侧另写一份默认值
ConnectionOptions defaultConnectionOptions() =>
    RustLib.instance.api.crateApiOptionsDefaultConnectionOptions();

/// 用户确认指纹后信任这台主机：写进 known_hosts。只认这次运行里连接时见过的那把密钥
Future<void> trustHostKey({
  required String host,
  required int port,
  required String fingerprint,
}) => RustLib.instance.api.crateApiOptionsTrustHostKey(
  host: host,
  port: port,
  fingerprint: fingerprint,
);

class ConnectionOptions {
  final SslOptions ssl;
  final TimeoutOptions timeouts;
  final SshOptions ssh;

  const ConnectionOptions({
    required this.ssl,
    required this.timeouts,
    required this.ssh,
  });

  @override
  int get hashCode => ssl.hashCode ^ timeouts.hashCode ^ ssh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionOptions &&
          runtimeType == other.runtimeType &&
          ssl == other.ssl &&
          timeouts == other.timeouts &&
          ssh == other.ssh;
}

class HostKeyIssue {
  final String host;
  final int port;
  final String fingerprint;
  final String algorithm;
  final HostKeyIssueKind kind;

  const HostKeyIssue({
    required this.host,
    required this.port,
    required this.fingerprint,
    required this.algorithm,
    required this.kind,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      fingerprint.hashCode ^
      algorithm.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostKeyIssue &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          fingerprint == other.fingerprint &&
          algorithm == other.algorithm &&
          kind == other.kind;
}

enum HostKeyIssueKind { unknown, mismatch }

@freezed
sealed class SshAuth with _$SshAuth {
  const SshAuth._();

  const factory SshAuth.password() = SshAuth_Password;
  const factory SshAuth.privateKey({required String path}) = SshAuth_PrivateKey;
  const factory SshAuth.agent() = SshAuth_Agent;
}

class SshHop {
  final String host;
  final int port;
  final String user;
  final SshAuth auth;

  const SshHop({
    required this.host,
    required this.port,
    required this.user,
    required this.auth,
  });

  @override
  int get hashCode =>
      host.hashCode ^ port.hashCode ^ user.hashCode ^ auth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshHop &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          user == other.user &&
          auth == other.auth;
}

class SshOptions {
  final List<SshHop> hops;

  const SshOptions({required this.hops});

  @override
  int get hashCode => hops.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SshOptions &&
          runtimeType == other.runtimeType &&
          hops == other.hops;
}

enum SslMode { disabled, required_, verifyIdentity }

class SslOptions {
  final SslMode mode;
  final String? caPath;
  final String? certPath;
  final String? keyPath;

  const SslOptions({
    required this.mode,
    this.caPath,
    this.certPath,
    this.keyPath,
  });

  @override
  int get hashCode =>
      mode.hashCode ^ caPath.hashCode ^ certPath.hashCode ^ keyPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SslOptions &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          caPath == other.caPath &&
          certPath == other.certPath &&
          keyPath == other.keyPath;
}

class TimeoutOptions {
  final int? connectSecs;
  final int? querySecs;

  const TimeoutOptions({this.connectSecs, this.querySecs});

  @override
  int get hashCode => connectSecs.hashCode ^ querySecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimeoutOptions &&
          runtimeType == other.runtimeType &&
          connectSecs == other.connectSecs &&
          querySecs == other.querySecs;
}
