// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 没存过就是默认值；存的值不合法报错
Future<Preferences> loadPreferences() =>
    RustLib.instance.api.crateApiPreferencesLoadPreferences();

Future<void> savePreferences({required Preferences preferences}) => RustLib
    .instance
    .api
    .crateApiPreferencesSavePreferences(preferences: preferences);

/// 默认值也由 core 给，Dart 侧不另写一份
Preferences defaultPreferences() =>
    RustLib.instance.api.crateApiPreferencesDefaultPreferences();

class Preferences {
  final ThemeMode theme;
  final int editorFontSize;
  final BigInt maxRows;
  final bool restoreConnections;
  final int transcriptHistoryLimit;
  final int queryHistoryLimit;
  final bool saveQueryHistory;

  const Preferences({
    required this.theme,
    required this.editorFontSize,
    required this.maxRows,
    required this.restoreConnections,
    required this.transcriptHistoryLimit,
    required this.queryHistoryLimit,
    required this.saveQueryHistory,
  });

  @override
  int get hashCode =>
      theme.hashCode ^
      editorFontSize.hashCode ^
      maxRows.hashCode ^
      restoreConnections.hashCode ^
      transcriptHistoryLimit.hashCode ^
      queryHistoryLimit.hashCode ^
      saveQueryHistory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Preferences &&
          runtimeType == other.runtimeType &&
          theme == other.theme &&
          editorFontSize == other.editorFontSize &&
          maxRows == other.maxRows &&
          restoreConnections == other.restoreConnections &&
          transcriptHistoryLimit == other.transcriptHistoryLimit &&
          queryHistoryLimit == other.queryHistoryLimit &&
          saveQueryHistory == other.saveQueryHistory;
}

enum ThemeMode { system, light, dark }
