// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'schema.freezed.dart';

/// 读到的结构转成可编辑的草稿，哪些列、索引锁住由 core 判定
TableDraft tableDraft({required TableStructure structure}) =>
    RustLib.instance.api.crateApiSchemaTableDraft(structure: structure);

/// 预览一批结构改动：语句、危险操作、执行须知
Future<AlterPlan> previewAlter({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableStructure original,
  required TableDraft draft,
}) => RustLib.instance.api.crateApiSchemaPreviewAlter(
  sessionId: sessionId,
  database: database,
  table: table,
  original: original,
  draft: draft,
);

/// 执行预览过的改动。statements 是预览时拿到的语句，重新生成的不一致就不执行
Future<void> applyAlter({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableStructure original,
  required TableDraft draft,
  required List<String> statements,
}) => RustLib.instance.api.crateApiSchemaApplyAlter(
  sessionId: sessionId,
  database: database,
  table: table,
  original: original,
  draft: draft,
  statements: statements,
);

/// 新建表的起始草稿：自增主键 id、InnoDB，默认值由 core 定
TableDraft newTableDraft() =>
    RustLib.instance.api.crateApiSchemaNewTableDraft();

/// 预览新建表。同名的表或视图已经存在就报错
Future<AlterPlan> previewCreateTable({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableDraft draft,
}) => RustLib.instance.api.crateApiSchemaPreviewCreateTable(
  sessionId: sessionId,
  database: database,
  table: table,
  draft: draft,
);

/// 执行预览过的建表。statements 是预览时拿到的语句，重新生成的不一致就不执行
Future<void> createTable({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableDraft draft,
  required List<String> statements,
}) => RustLib.instance.api.crateApiSchemaCreateTable(
  sessionId: sessionId,
  database: database,
  table: table,
  draft: draft,
  statements: statements,
);

/// 一张表的列、索引、外键和建表语句，结构页一次取齐
Future<TableStructure> tableStructure({
  required BigInt sessionId,
  required String database,
  required String table,
}) => RustLib.instance.api.crateApiSchemaTableStructure(
  sessionId: sessionId,
  database: database,
  table: table,
);

/// 服务器上的库列表
Future<List<String>> listDatabases({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSchemaListDatabases(sessionId: sessionId);

/// 某个库的表和视图
Future<List<TableInfo>> listTables({
  required BigInt sessionId,
  required String database,
}) => RustLib.instance.api.crateApiSchemaListTables(
  sessionId: sessionId,
  database: database,
);

/// 浏览整张表的 SQL。标识符转义在 core 里做，界面不要自己拼
Future<String> browseSql({required String table}) =>
    RustLib.instance.api.crateApiSchemaBrowseSql(table: table);

/// 预览侧栏右键的表操作（改名、复制、删除、清空）：语句、危险操作、执行须知
Future<AlterPlan> previewTableAction({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableAction action,
}) => RustLib.instance.api.crateApiSchemaPreviewTableAction(
  sessionId: sessionId,
  database: database,
  table: table,
  action: action,
);

/// 执行预览过的表操作。statements 是预览时拿到的语句，重新生成的不一致就不执行
Future<void> applyTableAction({
  required BigInt sessionId,
  required String database,
  required String table,
  required TableAction action,
  required List<String> statements,
}) => RustLib.instance.api.crateApiSchemaApplyTableAction(
  sessionId: sessionId,
  database: database,
  table: table,
  action: action,
  statements: statements,
);

/// 精确行数（真的 COUNT(*)，大表会慢）
Future<BigInt> countRows({
  required BigInt sessionId,
  required String database,
  required String table,
}) => RustLib.instance.api.crateApiSchemaCountRows(
  sessionId: sessionId,
  database: database,
  table: table,
);

/// ANALYZE / CHECK / OPTIMIZE / REPAIR TABLE，返回 MySQL 给的消息
Future<List<MaintenanceMessage>> runMaintenance({
  required BigInt sessionId,
  required String database,
  required String table,
  required Maintenance op,
}) => RustLib.instance.api.crateApiSchemaRunMaintenance(
  sessionId: sessionId,
  database: database,
  table: table,
  op: op,
);

/// 这张表的 INSERT 模板
Future<String> insertTemplate({
  required BigInt sessionId,
  required String database,
  required String table,
}) => RustLib.instance.api.crateApiSchemaInsertTemplate(
  sessionId: sessionId,
  database: database,
  table: table,
);

class AlterPlan {
  final List<String> statements;
  final List<String> dangers;
  final List<String> notes;

  const AlterPlan({
    required this.statements,
    required this.dangers,
    required this.notes,
  });

  @override
  int get hashCode => statements.hashCode ^ dangers.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AlterPlan &&
          runtimeType == other.runtimeType &&
          statements == other.statements &&
          dangers == other.dangers &&
          notes == other.notes;
}

class CheckDef {
  final String name;
  final String expression;
  final bool enforced;

  const CheckDef({
    required this.name,
    required this.expression,
    required this.enforced,
  });

  @override
  int get hashCode => name.hashCode ^ expression.hashCode ^ enforced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          expression == other.expression &&
          enforced == other.enforced;
}

class CheckDraft {
  final String? originalName;
  final String name;
  final String expression;
  final bool enforced;

  const CheckDraft({
    this.originalName,
    required this.name,
    required this.expression,
    required this.enforced,
  });

  @override
  int get hashCode =>
      originalName.hashCode ^
      name.hashCode ^
      expression.hashCode ^
      enforced.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CheckDraft &&
          runtimeType == other.runtimeType &&
          originalName == other.originalName &&
          name == other.name &&
          expression == other.expression &&
          enforced == other.enforced;
}

class ColumnDef {
  final String name;
  final String columnType;
  final bool nullable;
  final DefaultValue default_;
  final String extra;
  final String comment;
  final String? collation;

  const ColumnDef({
    required this.name,
    required this.columnType,
    required this.nullable,
    required this.default_,
    required this.extra,
    required this.comment,
    this.collation,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      columnType.hashCode ^
      nullable.hashCode ^
      default_.hashCode ^
      extra.hashCode ^
      comment.hashCode ^
      collation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          columnType == other.columnType &&
          nullable == other.nullable &&
          default_ == other.default_ &&
          extra == other.extra &&
          comment == other.comment &&
          collation == other.collation;
}

class ColumnDraft {
  final String? originalName;
  final String name;
  final String columnType;
  final bool nullable;
  final DefaultValue default_;
  final bool autoIncrement;
  final String? onUpdate;
  final String comment;
  final String? collation;
  final String? locked;

  const ColumnDraft({
    this.originalName,
    required this.name,
    required this.columnType,
    required this.nullable,
    required this.default_,
    required this.autoIncrement,
    this.onUpdate,
    required this.comment,
    this.collation,
    this.locked,
  });

  @override
  int get hashCode =>
      originalName.hashCode ^
      name.hashCode ^
      columnType.hashCode ^
      nullable.hashCode ^
      default_.hashCode ^
      autoIncrement.hashCode ^
      onUpdate.hashCode ^
      comment.hashCode ^
      collation.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnDraft &&
          runtimeType == other.runtimeType &&
          originalName == other.originalName &&
          name == other.name &&
          columnType == other.columnType &&
          nullable == other.nullable &&
          default_ == other.default_ &&
          autoIncrement == other.autoIncrement &&
          onUpdate == other.onUpdate &&
          comment == other.comment &&
          collation == other.collation &&
          locked == other.locked;
}

@freezed
sealed class DefaultValue with _$DefaultValue {
  const DefaultValue._();

  const factory DefaultValue.noDefault() = DefaultValue_NoDefault;
  const factory DefaultValue.null_() = DefaultValue_Null;
  const factory DefaultValue.literal(String field0) = DefaultValue_Literal;
  const factory DefaultValue.expression(String field0) =
      DefaultValue_Expression;
}

class ForeignKeyDef {
  final String name;
  final List<String> columns;
  final String referencedSchema;
  final String referencedTable;
  final List<String> referencedColumns;
  final String onUpdate;
  final String onDelete;

  const ForeignKeyDef({
    required this.name,
    required this.columns,
    required this.referencedSchema,
    required this.referencedTable,
    required this.referencedColumns,
    required this.onUpdate,
    required this.onDelete,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      columns.hashCode ^
      referencedSchema.hashCode ^
      referencedTable.hashCode ^
      referencedColumns.hashCode ^
      onUpdate.hashCode ^
      onDelete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForeignKeyDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          columns == other.columns &&
          referencedSchema == other.referencedSchema &&
          referencedTable == other.referencedTable &&
          referencedColumns == other.referencedColumns &&
          onUpdate == other.onUpdate &&
          onDelete == other.onDelete;
}

class ForeignKeyDraft {
  final String? originalName;
  final String name;
  final List<String> columns;
  final String referencedSchema;
  final String referencedTable;
  final List<String> referencedColumns;
  final String onUpdate;
  final String onDelete;

  const ForeignKeyDraft({
    this.originalName,
    required this.name,
    required this.columns,
    required this.referencedSchema,
    required this.referencedTable,
    required this.referencedColumns,
    required this.onUpdate,
    required this.onDelete,
  });

  @override
  int get hashCode =>
      originalName.hashCode ^
      name.hashCode ^
      columns.hashCode ^
      referencedSchema.hashCode ^
      referencedTable.hashCode ^
      referencedColumns.hashCode ^
      onUpdate.hashCode ^
      onDelete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ForeignKeyDraft &&
          runtimeType == other.runtimeType &&
          originalName == other.originalName &&
          name == other.name &&
          columns == other.columns &&
          referencedSchema == other.referencedSchema &&
          referencedTable == other.referencedTable &&
          referencedColumns == other.referencedColumns &&
          onUpdate == other.onUpdate &&
          onDelete == other.onDelete;
}

class IndexDef {
  final String name;
  final bool unique;
  final List<String> columns;
  final List<IndexPart> parts;
  final String indexType;
  final String comment;

  const IndexDef({
    required this.name,
    required this.unique,
    required this.columns,
    required this.parts,
    required this.indexType,
    required this.comment,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      unique.hashCode ^
      columns.hashCode ^
      parts.hashCode ^
      indexType.hashCode ^
      comment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexDef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          unique == other.unique &&
          columns == other.columns &&
          parts == other.parts &&
          indexType == other.indexType &&
          comment == other.comment;
}

class IndexDraft {
  final String? originalName;
  final String name;
  final IndexKind kind;
  final List<IndexPart> parts;
  final String comment;
  final String? locked;

  const IndexDraft({
    this.originalName,
    required this.name,
    required this.kind,
    required this.parts,
    required this.comment,
    this.locked,
  });

  @override
  int get hashCode =>
      originalName.hashCode ^
      name.hashCode ^
      kind.hashCode ^
      parts.hashCode ^
      comment.hashCode ^
      locked.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexDraft &&
          runtimeType == other.runtimeType &&
          originalName == other.originalName &&
          name == other.name &&
          kind == other.kind &&
          parts == other.parts &&
          comment == other.comment &&
          locked == other.locked;
}

enum IndexKind { primary, unique, normal, fulltext, spatial }

class IndexPart {
  final String? column;
  final int? prefix;
  final bool descending;

  const IndexPart({this.column, this.prefix, required this.descending});

  @override
  int get hashCode => column.hashCode ^ prefix.hashCode ^ descending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexPart &&
          runtimeType == other.runtimeType &&
          column == other.column &&
          prefix == other.prefix &&
          descending == other.descending;
}

enum Maintenance { analyze, check, optimize, repair }

class MaintenanceMessage {
  final String msgType;
  final String text;

  const MaintenanceMessage({required this.msgType, required this.text});

  @override
  int get hashCode => msgType.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MaintenanceMessage &&
          runtimeType == other.runtimeType &&
          msgType == other.msgType &&
          text == other.text;
}

@freezed
sealed class TableAction with _$TableAction {
  const TableAction._();

  const factory TableAction.rename({required String newName}) =
      TableAction_Rename;
  const factory TableAction.duplicate({
    required String newName,
    required bool withData,
  }) = TableAction_Duplicate;
  const factory TableAction.drop() = TableAction_Drop;
  const factory TableAction.truncate() = TableAction_Truncate;
}

class TableDraft {
  final List<ColumnDraft> columns;
  final List<IndexDraft> indexes;
  final List<ForeignKeyDraft> foreignKeys;
  final List<CheckDraft> checks;
  final TableOptionsDraft options;

  const TableDraft({
    required this.columns,
    required this.indexes,
    required this.foreignKeys,
    required this.checks,
    required this.options,
  });

  @override
  int get hashCode =>
      columns.hashCode ^
      indexes.hashCode ^
      foreignKeys.hashCode ^
      checks.hashCode ^
      options.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableDraft &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          indexes == other.indexes &&
          foreignKeys == other.foreignKeys &&
          checks == other.checks &&
          options == other.options;
}

class TableInfo {
  final String name;
  final BigInt estimatedRows;
  final bool isView;

  const TableInfo({
    required this.name,
    required this.estimatedRows,
    required this.isView,
  });

  @override
  int get hashCode => name.hashCode ^ estimatedRows.hashCode ^ isView.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          estimatedRows == other.estimatedRows &&
          isView == other.isView;
}

class TableOptionsDraft {
  final String engine;
  final String? charset;
  final String? collation;
  final String comment;
  final BigInt? autoIncrement;
  final String? rowFormat;
  final bool convertCharset;

  const TableOptionsDraft({
    required this.engine,
    this.charset,
    this.collation,
    required this.comment,
    this.autoIncrement,
    this.rowFormat,
    required this.convertCharset,
  });

  @override
  int get hashCode =>
      engine.hashCode ^
      charset.hashCode ^
      collation.hashCode ^
      comment.hashCode ^
      autoIncrement.hashCode ^
      rowFormat.hashCode ^
      convertCharset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableOptionsDraft &&
          runtimeType == other.runtimeType &&
          engine == other.engine &&
          charset == other.charset &&
          collation == other.collation &&
          comment == other.comment &&
          autoIncrement == other.autoIncrement &&
          rowFormat == other.rowFormat &&
          convertCharset == other.convertCharset;
}

class TableStructure {
  final List<ColumnDef> columns;
  final List<IndexDef> indexes;
  final List<ForeignKeyDef> foreignKeys;
  final String createSql;
  final String? tableCollation;
  final String? tableCharset;
  final String? engine;
  final String tableComment;
  final BigInt? autoIncrement;
  final String? rowFormat;
  final List<CheckDef>? checks;

  const TableStructure({
    required this.columns,
    required this.indexes,
    required this.foreignKeys,
    required this.createSql,
    this.tableCollation,
    this.tableCharset,
    this.engine,
    required this.tableComment,
    this.autoIncrement,
    this.rowFormat,
    this.checks,
  });

  @override
  int get hashCode =>
      columns.hashCode ^
      indexes.hashCode ^
      foreignKeys.hashCode ^
      createSql.hashCode ^
      tableCollation.hashCode ^
      tableCharset.hashCode ^
      engine.hashCode ^
      tableComment.hashCode ^
      autoIncrement.hashCode ^
      rowFormat.hashCode ^
      checks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableStructure &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          indexes == other.indexes &&
          foreignKeys == other.foreignKeys &&
          createSql == other.createSql &&
          tableCollation == other.tableCollation &&
          tableCharset == other.tableCharset &&
          engine == other.engine &&
          tableComment == other.tableComment &&
          autoIncrement == other.autoIncrement &&
          rowFormat == other.rowFormat &&
          checks == other.checks;
}
