// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// 服务器上的库列表
Future<List<String>> listDatabases({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiSchemaListDatabases(sessionId: sessionId);

/// 某个库的表和视图
Future<List<TableInfo>> listTables({
  required BigInt sessionId,
  required String database,
}) => RustLib.instance.api.crateApiSchemaListTables(
  sessionId: sessionId,
  database: database,
);

/// 浏览整张表的 SQL。标识符转义在 core 里做，界面不要自己拼
Future<String> browseSql({required String table}) =>
    RustLib.instance.api.crateApiSchemaBrowseSql(table: table);

/// 给查询加排序。包子查询而不是改原句，原 SQL 里已有的 ORDER BY / LIMIT 都不受影响
Future<String> withOrderBy({
  required String sql,
  required String column,
  required bool ascending,
}) => RustLib.instance.api.crateApiSchemaWithOrderBy(
  sql: sql,
  column: column,
  ascending: ascending,
);

class TableInfo {
  final String name;
  final BigInt estimatedRows;
  final bool isView;

  const TableInfo({
    required this.name,
    required this.estimatedRows,
    required this.isView,
  });

  @override
  int get hashCode => name.hashCode ^ estimatedRows.hashCode ^ isView.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          estimatedRows == other.estimatedRows &&
          isView == other.isView;
}
