// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'value.dart';

/// 进程列表，CData 自己的连接标了 is_own
Future<ProcessList> serverProcesses({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiServerServerProcesses(sessionId: sessionId);

/// KILL QUERY / KILL CONNECTION。target 是用户确认时看到的那一行，和现在对不上 core 会拒绝
Future<void> killProcess({
  required BigInt sessionId,
  required ProcessInfo target,
  required KillMode mode,
}) => RustLib.instance.api.crateApiServerKillProcess(
  sessionId: sessionId,
  target: target,
  mode: mode,
);

Future<VariableList> serverVariables({
  required BigInt sessionId,
  required VariableScope scope,
}) => RustLib.instance.api.crateApiServerServerVariables(
  sessionId: sessionId,
  scope: scope,
);

/// SHOW GLOBAL STATUS。previous 是上一次拿到的快照，差值和每秒增量按它算
Future<StatusSnapshot> serverStatus({
  required BigInt sessionId,
  StatusSnapshot? previous,
}) => RustLib.instance.api.crateApiServerServerStatus(
  sessionId: sessionId,
  previous: previous,
);

Future<SlowLogConfig> slowLogConfig({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiServerSlowLogConfig(sessionId: sessionId);

Future<List<SlowLogEntry>> slowLogEntries({
  required BigInt sessionId,
  required int limit,
}) => RustLib.instance.api.crateApiServerSlowLogEntries(
  sessionId: sessionId,
  limit: limit,
);

/// 预览 SET GLOBAL：语句、现在的值、影响范围
Future<SetVariablePlan> previewSetGlobal({
  required BigInt sessionId,
  required String name,
  required String value,
}) => RustLib.instance.api.crateApiServerPreviewSetGlobal(
  sessionId: sessionId,
  name: name,
  value: value,
);

/// 执行预览过的 SET GLOBAL，返回服务器存下的新值。statement 是预览拿到的语句
Future<DisplayCell> applySetGlobal({
  required BigInt sessionId,
  required String name,
  required String value,
  required String statement,
}) => RustLib.instance.api.crateApiServerApplySetGlobal(
  sessionId: sessionId,
  name: name,
  value: value,
  statement: statement,
);

enum KillMode { query, connection }

class ProcessInfo {
  final BigInt id;
  final DisplayCell user;
  final DisplayCell host;
  final DisplayCell db;
  final DisplayCell command;
  final DisplayCell time;
  final DisplayCell state;
  final DisplayCell info;
  final bool isOwn;

  const ProcessInfo({
    required this.id,
    required this.user,
    required this.host,
    required this.db,
    required this.command,
    required this.time,
    required this.state,
    required this.info,
    required this.isOwn,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      user.hashCode ^
      host.hashCode ^
      db.hashCode ^
      command.hashCode ^
      time.hashCode ^
      state.hashCode ^
      info.hashCode ^
      isOwn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          user == other.user &&
          host == other.host &&
          db == other.db &&
          command == other.command &&
          time == other.time &&
          state == other.state &&
          info == other.info &&
          isOwn == other.isOwn;
}

class ProcessList {
  final List<ProcessInfo> processes;
  final bool truncated;
  final String? notice;

  const ProcessList({
    required this.processes,
    required this.truncated,
    this.notice,
  });

  @override
  int get hashCode => processes.hashCode ^ truncated.hashCode ^ notice.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessList &&
          runtimeType == other.runtimeType &&
          processes == other.processes &&
          truncated == other.truncated &&
          notice == other.notice;
}

class SetVariablePlan {
  final String statement;
  final DisplayCell currentValue;
  final List<String> warnings;

  const SetVariablePlan({
    required this.statement,
    required this.currentValue,
    required this.warnings,
  });

  @override
  int get hashCode =>
      statement.hashCode ^ currentValue.hashCode ^ warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SetVariablePlan &&
          runtimeType == other.runtimeType &&
          statement == other.statement &&
          currentValue == other.currentValue &&
          warnings == other.warnings;
}

class SlowLogConfig {
  final DisplayCell slowQueryLog;
  final DisplayCell logOutput;
  final DisplayCell longQueryTime;
  final DisplayCell slowQueryLogFile;
  final bool enabled;
  final String? tableUnavailable;

  const SlowLogConfig({
    required this.slowQueryLog,
    required this.logOutput,
    required this.longQueryTime,
    required this.slowQueryLogFile,
    required this.enabled,
    this.tableUnavailable,
  });

  @override
  int get hashCode =>
      slowQueryLog.hashCode ^
      logOutput.hashCode ^
      longQueryTime.hashCode ^
      slowQueryLogFile.hashCode ^
      enabled.hashCode ^
      tableUnavailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlowLogConfig &&
          runtimeType == other.runtimeType &&
          slowQueryLog == other.slowQueryLog &&
          logOutput == other.logOutput &&
          longQueryTime == other.longQueryTime &&
          slowQueryLogFile == other.slowQueryLogFile &&
          enabled == other.enabled &&
          tableUnavailable == other.tableUnavailable;
}

class SlowLogEntry {
  final DisplayCell startTime;
  final DisplayCell userHost;
  final DisplayCell queryTime;
  final DisplayCell lockTime;
  final DisplayCell rowsSent;
  final DisplayCell rowsExamined;
  final DisplayCell db;
  final DisplayCell sqlText;

  const SlowLogEntry({
    required this.startTime,
    required this.userHost,
    required this.queryTime,
    required this.lockTime,
    required this.rowsSent,
    required this.rowsExamined,
    required this.db,
    required this.sqlText,
  });

  @override
  int get hashCode =>
      startTime.hashCode ^
      userHost.hashCode ^
      queryTime.hashCode ^
      lockTime.hashCode ^
      rowsSent.hashCode ^
      rowsExamined.hashCode ^
      db.hashCode ^
      sqlText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlowLogEntry &&
          runtimeType == other.runtimeType &&
          startTime == other.startTime &&
          userHost == other.userHost &&
          queryTime == other.queryTime &&
          lockTime == other.lockTime &&
          rowsSent == other.rowsSent &&
          rowsExamined == other.rowsExamined &&
          db == other.db &&
          sqlText == other.sqlText;
}

class StatusCounter {
  final String name;
  final DisplayCell value;
  final String? delta;
  final String? rate;

  const StatusCounter({
    required this.name,
    required this.value,
    this.delta,
    this.rate,
  });

  @override
  int get hashCode =>
      name.hashCode ^ value.hashCode ^ delta.hashCode ^ rate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusCounter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value &&
          delta == other.delta &&
          rate == other.rate;
}

class StatusSnapshot {
  final BigInt takenAtMs;
  final List<StatusCounter> counters;
  final bool truncated;

  const StatusSnapshot({
    required this.takenAtMs,
    required this.counters,
    required this.truncated,
  });

  @override
  int get hashCode =>
      takenAtMs.hashCode ^ counters.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StatusSnapshot &&
          runtimeType == other.runtimeType &&
          takenAtMs == other.takenAtMs &&
          counters == other.counters &&
          truncated == other.truncated;
}

class Variable {
  final String name;
  final DisplayCell value;

  const Variable({required this.name, required this.value});

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Variable &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class VariableList {
  final List<Variable> variables;
  final bool truncated;

  const VariableList({required this.variables, required this.truncated});

  @override
  int get hashCode => variables.hashCode ^ truncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VariableList &&
          runtimeType == other.runtimeType &&
          variables == other.variables &&
          truncated == other.truncated;
}

enum VariableScope { global, session }
