// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'users.freezed.dart';

/// 用户管理页打开时的全部信息，一次取齐
Future<UserAdmin> loadUserAdmin({required BigInt sessionId}) =>
    RustLib.instance.api.crateApiUsersLoadUserAdmin(sessionId: sessionId);

/// 一个账号的 SHOW GRANTS：分层的项和原文
Future<AccountGrants> accountGrants({
  required BigInt sessionId,
  required Account account,
}) => RustLib.instance.api.crateApiUsersAccountGrants(
  sessionId: sessionId,
  account: account,
);

/// 预览变更。password 只有新建和改密码时给
Future<ChangePlan> previewUserChange({
  required BigInt sessionId,
  required UserChange change,
  String? password,
}) => RustLib.instance.api.crateApiUsersPreviewUserChange(
  sessionId: sessionId,
  change: change,
  password: password,
);

/// 执行预览过的变更。statement 是预览时拿到的语句
Future<void> applyUserChange({
  required BigInt sessionId,
  required UserChange change,
  String? password,
  required String statement,
}) => RustLib.instance.api.crateApiUsersApplyUserChange(
  sessionId: sessionId,
  change: change,
  password: password,
  statement: statement,
);

class Account {
  final String user;
  final String host;

  const Account({required this.user, required this.host});

  @override
  int get hashCode => user.hashCode ^ host.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Account &&
          runtimeType == other.runtimeType &&
          user == other.user &&
          host == other.host;
}

class AccountGrants {
  final List<GrantEntry> entries;
  final List<String> statements;

  const AccountGrants({required this.entries, required this.statements});

  @override
  int get hashCode => entries.hashCode ^ statements.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountGrants &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          statements == other.statements;
}

class ChangePlan {
  final String statement;
  final List<String> dangers;
  final List<String> notes;

  const ChangePlan({
    required this.statement,
    required this.dangers,
    required this.notes,
  });

  @override
  int get hashCode => statement.hashCode ^ dangers.hashCode ^ notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChangePlan &&
          runtimeType == other.runtimeType &&
          statement == other.statement &&
          dangers == other.dangers &&
          notes == other.notes;
}

class GrantEntry {
  final GrantScope scope;
  final String target;
  final List<String> privileges;
  final bool grantOption;
  final bool partialRevoke;
  final Account? role;
  final String statement;

  const GrantEntry({
    required this.scope,
    required this.target,
    required this.privileges,
    required this.grantOption,
    required this.partialRevoke,
    this.role,
    required this.statement,
  });

  @override
  int get hashCode =>
      scope.hashCode ^
      target.hashCode ^
      privileges.hashCode ^
      grantOption.hashCode ^
      partialRevoke.hashCode ^
      role.hashCode ^
      statement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GrantEntry &&
          runtimeType == other.runtimeType &&
          scope == other.scope &&
          target == other.target &&
          privileges == other.privileges &&
          grantOption == other.grantOption &&
          partialRevoke == other.partialRevoke &&
          role == other.role &&
          statement == other.statement;
}

@freezed
sealed class GrantLevel with _$GrantLevel {
  const GrantLevel._();

  const factory GrantLevel.global() = GrantLevel_Global;
  const factory GrantLevel.database({required String database}) =
      GrantLevel_Database;
  const factory GrantLevel.table({
    required String database,
    required String table,
  }) = GrantLevel_Table;
}

enum GrantScope {
  global,
  database,
  table,
  column,
  routine,
  role,
  proxy,
  unparsed,
}

class UserAdmin {
  final Account current;
  final List<UserRow> users;
  final String? usersUnavailable;
  final List<String> plugins;
  final List<String> globalPrivileges;
  final List<String> databasePrivileges;
  final List<String> tablePrivileges;

  const UserAdmin({
    required this.current,
    required this.users,
    this.usersUnavailable,
    required this.plugins,
    required this.globalPrivileges,
    required this.databasePrivileges,
    required this.tablePrivileges,
  });

  @override
  int get hashCode =>
      current.hashCode ^
      users.hashCode ^
      usersUnavailable.hashCode ^
      plugins.hashCode ^
      globalPrivileges.hashCode ^
      databasePrivileges.hashCode ^
      tablePrivileges.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserAdmin &&
          runtimeType == other.runtimeType &&
          current == other.current &&
          users == other.users &&
          usersUnavailable == other.usersUnavailable &&
          plugins == other.plugins &&
          globalPrivileges == other.globalPrivileges &&
          databasePrivileges == other.databasePrivileges &&
          tablePrivileges == other.tablePrivileges;
}

@freezed
sealed class UserChange with _$UserChange {
  const UserChange._();

  const factory UserChange.create({required Account account, String? plugin}) =
      UserChange_Create;
  const factory UserChange.setPassword({required Account account}) =
      UserChange_SetPassword;
  const factory UserChange.setLocked({
    required Account account,
    required bool locked,
  }) = UserChange_SetLocked;
  const factory UserChange.drop({required Account account}) = UserChange_Drop;
  const factory UserChange.grant({
    required Account account,
    required GrantLevel level,
    required List<String> privileges,
    required bool withGrantOption,
  }) = UserChange_Grant;
  const factory UserChange.revoke({
    required Account account,
    required GrantLevel level,
    required List<String> privileges,
  }) = UserChange_Revoke;
  const factory UserChange.grantRole({
    required Account account,
    required Account role,
  }) = UserChange_GrantRole;
  const factory UserChange.revokeRole({
    required Account account,
    required Account role,
  }) = UserChange_RevokeRole;
}

class UserRow {
  final Account account;
  final String plugin;
  final bool locked;
  final String? passwordExpired;
  final bool isCurrent;

  const UserRow({
    required this.account,
    required this.plugin,
    required this.locked,
    this.passwordExpired,
    required this.isCurrent,
  });

  @override
  int get hashCode =>
      account.hashCode ^
      plugin.hashCode ^
      locked.hashCode ^
      passwordExpired.hashCode ^
      isCurrent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserRow &&
          runtimeType == other.runtimeType &&
          account == other.account &&
          plugin == other.plugin &&
          locked == other.locked &&
          passwordExpired == other.passwordExpired &&
          isCurrent == other.isCurrent;
}
