// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'value.freezed.dart';

/// 单元格在网格里的显示文本
Future<String> displayText({required CellValue value}) =>
    RustLib.instance.api.crateApiValueDisplayText(value: value);

@freezed
sealed class CellValue with _$CellValue {
  const CellValue._();

  const factory CellValue.null_() = CellValue_Null;
  const factory CellValue.int(PlatformInt64 field0) = CellValue_Int;
  const factory CellValue.uInt(BigInt field0) = CellValue_UInt;
  const factory CellValue.double(double field0) = CellValue_Double;
  const factory CellValue.text(String field0) = CellValue_Text;
  const factory CellValue.bytes(Uint8List field0) = CellValue_Bytes;
  const factory CellValue.invalidText(Uint8List field0) = CellValue_InvalidText;
}
