// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'value.freezed.dart';

/// 格式化 JSON，同时校验。不合法返回带行列号的错误
Future<String> formatJson({required String text}) =>
    RustLib.instance.api.crateApiValueFormatJson(text: text);

/// 二进制内容的十六进制视图，超过 limit 字节只显示前面并注明总长
Future<String> hexDump({required List<int> bytes, required BigInt limit}) =>
    RustLib.instance.api.crateApiValueHexDump(bytes: bytes, limit: limit);

/// 单元格在网格里的显示文本
Future<String> displayText({required CellValue value}) =>
    RustLib.instance.api.crateApiValueDisplayText(value: value);

@freezed
sealed class CellValue with _$CellValue {
  const CellValue._();

  const factory CellValue.null_() = CellValue_Null;
  const factory CellValue.int(PlatformInt64 field0) = CellValue_Int;
  const factory CellValue.uInt(BigInt field0) = CellValue_UInt;
  const factory CellValue.double(double field0) = CellValue_Double;
  const factory CellValue.text(String field0) = CellValue_Text;
  const factory CellValue.bytes(Uint8List field0) = CellValue_Bytes;
  const factory CellValue.invalidText(Uint8List field0) = CellValue_InvalidText;
}

class DisplayCell {
  final String text;
  final bool placeholder;

  const DisplayCell({required this.text, required this.placeholder});

  @override
  int get hashCode => text.hashCode ^ placeholder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayCell &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          placeholder == other.placeholder;
}
