// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connections.dart';
import 'api/db.dart';
import 'api/schema.dart';
import 'api/value.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 477168102;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cdata_rust',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDbApplyEdit({
    required BigInt sessionId,
    required BigInt rowIndex,
    required BigInt columnIndex,
    required CellValue newValue,
  });

  Future<String> crateApiSchemaBrowseSql({required String table});

  Future<void> crateApiDbCloseSession({required BigInt sessionId});

  Future<void> crateApiConnectionsDeleteConnection({required String id});

  Future<BigInt> crateApiDbDeleteRows({
    required BigInt sessionId,
    required Uint64List rowIndexes,
  });

  Future<String> crateApiValueDisplayText({required CellValue value});

  Future<QuerySummary> crateApiDbExecute({
    required BigInt sessionId,
    required String sql,
    required BigInt maxRows,
  });

  Future<List<List<CellValue>>> crateApiDbFetchWindow({
    required BigInt sessionId,
    required BigInt offset,
    required BigInt limit,
  });

  Future<List<List<String>>> crateApiDbFetchWindowText({
    required BigInt sessionId,
    required BigInt offset,
    required BigInt limit,
  });

  Future<void> crateApiInitApp();

  Future<BigInt> crateApiDbInsertRow({
    required BigInt sessionId,
    required List<CellValue?> values,
  });

  Future<List<SavedConnection>> crateApiConnectionsListConnections();

  Future<List<String>> crateApiSchemaListDatabases({required BigInt sessionId});

  Future<List<TableInfo>> crateApiSchemaListTables({
    required BigInt sessionId,
    required String database,
  });

  Future<String?> crateApiConnectionsLoadPassword({required String id});

  Future<BigInt> crateApiDbOpenSession({required ConnectionConfig config});

  Future<void> crateApiConnectionsSaveConnection({
    required SavedConnection connection,
    String? password,
  });

  Future<String> crateApiSchemaWithOrderBy({
    required String sql,
    required String column,
    required bool ascending,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDbApplyEdit({
    required BigInt sessionId,
    required BigInt rowIndex,
    required BigInt columnIndex,
    required CellValue newValue,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(rowIndex, serializer);
          sse_encode_u_64(columnIndex, serializer);
          sse_encode_box_autoadd_cell_value(newValue, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbApplyEditConstMeta,
        argValues: [sessionId, rowIndex, columnIndex, newValue],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbApplyEditConstMeta => const TaskConstMeta(
    debugName: "apply_edit",
    argNames: ["sessionId", "rowIndex", "columnIndex", "newValue"],
  );

  @override
  Future<String> crateApiSchemaBrowseSql({required String table}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(table, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSchemaBrowseSqlConstMeta,
        argValues: [table],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaBrowseSqlConstMeta =>
      const TaskConstMeta(debugName: "browse_sql", argNames: ["table"]);

  @override
  Future<void> crateApiDbCloseSession({required BigInt sessionId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbCloseSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbCloseSessionConstMeta =>
      const TaskConstMeta(debugName: "close_session", argNames: ["sessionId"]);

  @override
  Future<void> crateApiConnectionsDeleteConnection({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsDeleteConnectionConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsDeleteConnectionConstMeta =>
      const TaskConstMeta(debugName: "delete_connection", argNames: ["id"]);

  @override
  Future<BigInt> crateApiDbDeleteRows({
    required BigInt sessionId,
    required Uint64List rowIndexes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_prim_u_64_strict(rowIndexes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbDeleteRowsConstMeta,
        argValues: [sessionId, rowIndexes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDeleteRowsConstMeta => const TaskConstMeta(
    debugName: "delete_rows",
    argNames: ["sessionId", "rowIndexes"],
  );

  @override
  Future<String> crateApiValueDisplayText({required CellValue value}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_cell_value(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiValueDisplayTextConstMeta,
        argValues: [value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValueDisplayTextConstMeta =>
      const TaskConstMeta(debugName: "display_text", argNames: ["value"]);

  @override
  Future<QuerySummary> crateApiDbExecute({
    required BigInt sessionId,
    required String sql,
    required BigInt maxRows,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(sql, serializer);
          sse_encode_u_64(maxRows, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_query_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbExecuteConstMeta,
        argValues: [sessionId, sql, maxRows],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbExecuteConstMeta => const TaskConstMeta(
    debugName: "execute",
    argNames: ["sessionId", "sql", "maxRows"],
  );

  @override
  Future<List<List<CellValue>>> crateApiDbFetchWindow({
    required BigInt sessionId,
    required BigInt offset,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_u_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_cell_value,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbFetchWindowConstMeta,
        argValues: [sessionId, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbFetchWindowConstMeta => const TaskConstMeta(
    debugName: "fetch_window",
    argNames: ["sessionId", "offset", "limit"],
  );

  @override
  Future<List<List<String>>> crateApiDbFetchWindowText({
    required BigInt sessionId,
    required BigInt offset,
    required BigInt limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_64(offset, serializer);
          sse_encode_u_64(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbFetchWindowTextConstMeta,
        argValues: [sessionId, offset, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbFetchWindowTextConstMeta => const TaskConstMeta(
    debugName: "fetch_window_text",
    argNames: ["sessionId", "offset", "limit"],
  );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<BigInt> crateApiDbInsertRow({
    required BigInt sessionId,
    required List<CellValue?> values,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_list_opt_box_autoadd_cell_value(values, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDbInsertRowConstMeta,
        argValues: [sessionId, values],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbInsertRowConstMeta => const TaskConstMeta(
    debugName: "insert_row",
    argNames: ["sessionId", "values"],
  );

  @override
  Future<List<SavedConnection>> crateApiConnectionsListConnections() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_saved_connection,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsListConnectionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsListConnectionsConstMeta =>
      const TaskConstMeta(debugName: "list_connections", argNames: []);

  @override
  Future<List<String>> crateApiSchemaListDatabases({
    required BigInt sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSchemaListDatabasesConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaListDatabasesConstMeta =>
      const TaskConstMeta(debugName: "list_databases", argNames: ["sessionId"]);

  @override
  Future<List<TableInfo>> crateApiSchemaListTables({
    required BigInt sessionId,
    required String database,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_String(database, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_table_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSchemaListTablesConstMeta,
        argValues: [sessionId, database],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaListTablesConstMeta => const TaskConstMeta(
    debugName: "list_tables",
    argNames: ["sessionId", "database"],
  );

  @override
  Future<String?> crateApiConnectionsLoadPassword({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsLoadPasswordConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsLoadPasswordConstMeta =>
      const TaskConstMeta(debugName: "load_password", argNames: ["id"]);

  @override
  Future<BigInt> crateApiDbOpenSession({required ConnectionConfig config}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_connection_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDbOpenSessionConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbOpenSessionConstMeta =>
      const TaskConstMeta(debugName: "open_session", argNames: ["config"]);

  @override
  Future<void> crateApiConnectionsSaveConnection({
    required SavedConnection connection,
    String? password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_saved_connection(connection, serializer);
          sse_encode_opt_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectionsSaveConnectionConstMeta,
        argValues: [connection, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectionsSaveConnectionConstMeta =>
      const TaskConstMeta(
        debugName: "save_connection",
        argNames: ["connection", "password"],
      );

  @override
  Future<String> crateApiSchemaWithOrderBy({
    required String sql,
    required String column,
    required bool ascending,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sql, serializer);
          sse_encode_String(column, serializer);
          sse_encode_bool(ascending, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSchemaWithOrderByConstMeta,
        argValues: [sql, column, ascending],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSchemaWithOrderByConstMeta => const TaskConstMeta(
    debugName: "with_order_by",
    argNames: ["sql", "column", "ascending"],
  );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  CellValue dco_decode_box_autoadd_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_cell_value(raw);
  }

  @protected
  ConnectionConfig dco_decode_box_autoadd_connection_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_connection_config(raw);
  }

  @protected
  EditTarget dco_decode_box_autoadd_edit_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_edit_target(raw);
  }

  @protected
  SavedConnection dco_decode_box_autoadd_saved_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_saved_connection(raw);
  }

  @protected
  CellValue dco_decode_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return CellValue_Null();
      case 1:
        return CellValue_Int(dco_decode_i_64(raw[1]));
      case 2:
        return CellValue_UInt(dco_decode_u_64(raw[1]));
      case 3:
        return CellValue_Double(dco_decode_f_64(raw[1]));
      case 4:
        return CellValue_Text(dco_decode_String(raw[1]));
      case 5:
        return CellValue_Bytes(dco_decode_list_prim_u_8_strict(raw[1]));
      case 6:
        return CellValue_InvalidText(dco_decode_list_prim_u_8_strict(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  ColumnMeta dco_decode_column_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ColumnMeta(
      name: dco_decode_String(arr[0]),
      orgName: dco_decode_String(arr[1]),
      orgTable: dco_decode_String(arr[2]),
      schema: dco_decode_String(arr[3]),
      isBinary: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ConnectionConfig dco_decode_connection_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConnectionConfig(
      host: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      user: dco_decode_String(arr[2]),
      password: dco_decode_String(arr[3]),
      database: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  EditTarget dco_decode_edit_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EditTarget(
      schema: dco_decode_String(arr[0]),
      table: dco_decode_String(arr[1]),
      keyIndexes: dco_decode_list_prim_usize_strict(arr[2]),
    );
  }

  @protected
  Editability dco_decode_editability(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Editability_Editable(dco_decode_box_autoadd_edit_target(raw[1]));
      case 1:
        return Editability_ReadOnly(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CellValue> dco_decode_list_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_cell_value).toList();
  }

  @protected
  List<ColumnMeta> dco_decode_list_column_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_column_meta).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<List<CellValue>> dco_decode_list_list_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_cell_value).toList();
  }

  @protected
  List<CellValue?> dco_decode_list_opt_box_autoadd_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_opt_box_autoadd_cell_value)
        .toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint64List;
  }

  @protected
  List<SavedConnection> dco_decode_list_saved_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_saved_connection).toList();
  }

  @protected
  List<TableInfo> dco_decode_list_table_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_table_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  CellValue? dco_decode_opt_box_autoadd_cell_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_cell_value(raw);
  }

  @protected
  QuerySummary dco_decode_query_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return QuerySummary(
      columns: dco_decode_list_column_meta(arr[0]),
      totalRows: dco_decode_u_64(arr[1]),
      truncated: dco_decode_bool(arr[2]),
      editability: dco_decode_editability(arr[3]),
    );
  }

  @protected
  SavedConnection dco_decode_saved_connection(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SavedConnection(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      host: dco_decode_String(arr[2]),
      port: dco_decode_u_16(arr[3]),
      user: dco_decode_String(arr[4]),
      database: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  TableInfo dco_decode_table_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TableInfo(
      name: dco_decode_String(arr[0]),
      estimatedRows: dco_decode_u_64(arr[1]),
      isView: dco_decode_bool(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  CellValue sse_decode_box_autoadd_cell_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_cell_value(deserializer));
  }

  @protected
  ConnectionConfig sse_decode_box_autoadd_connection_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_connection_config(deserializer));
  }

  @protected
  EditTarget sse_decode_box_autoadd_edit_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_edit_target(deserializer));
  }

  @protected
  SavedConnection sse_decode_box_autoadd_saved_connection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_saved_connection(deserializer));
  }

  @protected
  CellValue sse_decode_cell_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return CellValue_Null();
      case 1:
        var var_field0 = sse_decode_i_64(deserializer);
        return CellValue_Int(var_field0);
      case 2:
        var var_field0 = sse_decode_u_64(deserializer);
        return CellValue_UInt(var_field0);
      case 3:
        var var_field0 = sse_decode_f_64(deserializer);
        return CellValue_Double(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return CellValue_Text(var_field0);
      case 5:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return CellValue_Bytes(var_field0);
      case 6:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return CellValue_InvalidText(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  ColumnMeta sse_decode_column_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_orgName = sse_decode_String(deserializer);
    var var_orgTable = sse_decode_String(deserializer);
    var var_schema = sse_decode_String(deserializer);
    var var_isBinary = sse_decode_bool(deserializer);
    return ColumnMeta(
      name: var_name,
      orgName: var_orgName,
      orgTable: var_orgTable,
      schema: var_schema,
      isBinary: var_isBinary,
    );
  }

  @protected
  ConnectionConfig sse_decode_connection_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_user = sse_decode_String(deserializer);
    var var_password = sse_decode_String(deserializer);
    var var_database = sse_decode_opt_String(deserializer);
    return ConnectionConfig(
      host: var_host,
      port: var_port,
      user: var_user,
      password: var_password,
      database: var_database,
    );
  }

  @protected
  EditTarget sse_decode_edit_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schema = sse_decode_String(deserializer);
    var var_table = sse_decode_String(deserializer);
    var var_keyIndexes = sse_decode_list_prim_usize_strict(deserializer);
    return EditTarget(
      schema: var_schema,
      table: var_table,
      keyIndexes: var_keyIndexes,
    );
  }

  @protected
  Editability sse_decode_editability(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_edit_target(deserializer);
        return Editability_Editable(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return Editability_ReadOnly(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CellValue> sse_decode_list_cell_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_cell_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<ColumnMeta> sse_decode_list_column_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ColumnMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_column_meta(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<CellValue>> sse_decode_list_list_cell_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<CellValue>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_cell_value(deserializer));
    }
    return ans_;
  }

  @protected
  List<CellValue?> sse_decode_list_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CellValue?>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_opt_box_autoadd_cell_value(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<SavedConnection> sse_decode_list_saved_connection(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SavedConnection>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_saved_connection(deserializer));
    }
    return ans_;
  }

  @protected
  List<TableInfo> sse_decode_list_table_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TableInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_table_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  CellValue? sse_decode_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_cell_value(deserializer));
    } else {
      return null;
    }
  }

  @protected
  QuerySummary sse_decode_query_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columns = sse_decode_list_column_meta(deserializer);
    var var_totalRows = sse_decode_u_64(deserializer);
    var var_truncated = sse_decode_bool(deserializer);
    var var_editability = sse_decode_editability(deserializer);
    return QuerySummary(
      columns: var_columns,
      totalRows: var_totalRows,
      truncated: var_truncated,
      editability: var_editability,
    );
  }

  @protected
  SavedConnection sse_decode_saved_connection(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_host = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_user = sse_decode_String(deserializer);
    var var_database = sse_decode_opt_String(deserializer);
    return SavedConnection(
      id: var_id,
      name: var_name,
      host: var_host,
      port: var_port,
      user: var_user,
      database: var_database,
    );
  }

  @protected
  TableInfo sse_decode_table_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_estimatedRows = sse_decode_u_64(deserializer);
    var var_isView = sse_decode_bool(deserializer);
    return TableInfo(
      name: var_name,
      estimatedRows: var_estimatedRows,
      isView: var_isView,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_cell_value(
    CellValue self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_cell_value(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_connection_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_edit_target(
    EditTarget self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_edit_target(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_saved_connection(self, serializer);
  }

  @protected
  void sse_encode_cell_value(CellValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case CellValue_Null():
        sse_encode_i_32(0, serializer);
      case CellValue_Int(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(field0, serializer);
      case CellValue_UInt(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_u_64(field0, serializer);
      case CellValue_Double(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_f_64(field0, serializer);
      case CellValue_Text(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case CellValue_Bytes(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
      case CellValue_InvalidText(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_column_meta(ColumnMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.orgName, serializer);
    sse_encode_String(self.orgTable, serializer);
    sse_encode_String(self.schema, serializer);
    sse_encode_bool(self.isBinary, serializer);
  }

  @protected
  void sse_encode_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.user, serializer);
    sse_encode_String(self.password, serializer);
    sse_encode_opt_String(self.database, serializer);
  }

  @protected
  void sse_encode_edit_target(EditTarget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.schema, serializer);
    sse_encode_String(self.table, serializer);
    sse_encode_list_prim_usize_strict(self.keyIndexes, serializer);
  }

  @protected
  void sse_encode_editability(Editability self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Editability_Editable(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_edit_target(field0, serializer);
      case Editability_ReadOnly(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_cell_value(
    List<CellValue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_cell_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_column_meta(
    List<ColumnMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_column_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_cell_value(
    List<List<CellValue>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_cell_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_opt_box_autoadd_cell_value(
    List<CellValue?> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_opt_box_autoadd_cell_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_saved_connection(
    List<SavedConnection> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_saved_connection(item, serializer);
    }
  }

  @protected
  void sse_encode_list_table_info(
    List<TableInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_table_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_cell_value(
    CellValue? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_cell_value(self, serializer);
    }
  }

  @protected
  void sse_encode_query_summary(QuerySummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_column_meta(self.columns, serializer);
    sse_encode_u_64(self.totalRows, serializer);
    sse_encode_bool(self.truncated, serializer);
    sse_encode_editability(self.editability, serializer);
  }

  @protected
  void sse_encode_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.host, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_String(self.user, serializer);
    sse_encode_opt_String(self.database, serializer);
  }

  @protected
  void sse_encode_table_info(TableInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_64(self.estimatedRows, serializer);
    sse_encode_bool(self.isView, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
