// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connections.dart';
import 'api/db.dart';
import 'api/editor.dart';
import 'api/layouts.dart';
import 'api/schema.dart';
import 'api/value.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CellValue dco_decode_box_autoadd_cell_value(dynamic raw);

  @protected
  ConnectionConfig dco_decode_box_autoadd_connection_config(dynamic raw);

  @protected
  EditTarget dco_decode_box_autoadd_edit_target(dynamic raw);

  @protected
  ExportOptions dco_decode_box_autoadd_export_options(dynamic raw);

  @protected
  SavedConnection dco_decode_box_autoadd_saved_connection(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CellValue dco_decode_cell_value(dynamic raw);

  @protected
  ColumnDef dco_decode_column_def(dynamic raw);

  @protected
  ColumnKind dco_decode_column_kind(dynamic raw);

  @protected
  ColumnLayout dco_decode_column_layout(dynamic raw);

  @protected
  ColumnMeta dco_decode_column_meta(dynamic raw);

  @protected
  Completion dco_decode_completion(dynamic raw);

  @protected
  CompletionItem dco_decode_completion_item(dynamic raw);

  @protected
  CompletionKind dco_decode_completion_kind(dynamic raw);

  @protected
  ConnectionConfig dco_decode_connection_config(dynamic raw);

  @protected
  DefaultValue dco_decode_default_value(dynamic raw);

  @protected
  EditTarget dco_decode_edit_target(dynamic raw);

  @protected
  Editability dco_decode_editability(dynamic raw);

  @protected
  ExportEncoding dco_decode_export_encoding(dynamic raw);

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  ExportOptions dco_decode_export_options(dynamic raw);

  @protected
  ExportSummary dco_decode_export_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Favorite dco_decode_favorite(dynamic raw);

  @protected
  FilterCondition dco_decode_filter_condition(dynamic raw);

  @protected
  FilterOp dco_decode_filter_op(dynamic raw);

  @protected
  ForeignKeyDef dco_decode_foreign_key_def(dynamic raw);

  @protected
  HistoryEntry dco_decode_history_entry(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  IndexDef dco_decode_index_def(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CellValue> dco_decode_list_cell_value(dynamic raw);

  @protected
  List<ColumnDef> dco_decode_list_column_def(dynamic raw);

  @protected
  List<ColumnLayout> dco_decode_list_column_layout(dynamic raw);

  @protected
  List<ColumnMeta> dco_decode_list_column_meta(dynamic raw);

  @protected
  List<CompletionItem> dco_decode_list_completion_item(dynamic raw);

  @protected
  List<Favorite> dco_decode_list_favorite(dynamic raw);

  @protected
  List<FilterCondition> dco_decode_list_filter_condition(dynamic raw);

  @protected
  List<ForeignKeyDef> dco_decode_list_foreign_key_def(dynamic raw);

  @protected
  List<HistoryEntry> dco_decode_list_history_entry(dynamic raw);

  @protected
  List<IndexDef> dco_decode_list_index_def(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<List<CellValue>> dco_decode_list_list_cell_value(dynamic raw);

  @protected
  List<CellValue?> dco_decode_list_opt_box_autoadd_cell_value(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<SavedConnection> dco_decode_list_saved_connection(dynamic raw);

  @protected
  List<SqlToken> dco_decode_list_sql_token(dynamic raw);

  @protected
  List<TableInfo> dco_decode_list_table_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CellValue? dco_decode_opt_box_autoadd_cell_value(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  QuerySummary dco_decode_query_summary(dynamic raw);

  @protected
  SavedConnection dco_decode_saved_connection(dynamic raw);

  @protected
  SqlToken dco_decode_sql_token(dynamic raw);

  @protected
  SqlTokenKind dco_decode_sql_token_kind(dynamic raw);

  @protected
  TableInfo dco_decode_table_info(dynamic raw);

  @protected
  TableStructure dco_decode_table_structure(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CellValue sse_decode_box_autoadd_cell_value(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_box_autoadd_connection_config(
    SseDeserializer deserializer,
  );

  @protected
  EditTarget sse_decode_box_autoadd_edit_target(SseDeserializer deserializer);

  @protected
  ExportOptions sse_decode_box_autoadd_export_options(
    SseDeserializer deserializer,
  );

  @protected
  SavedConnection sse_decode_box_autoadd_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CellValue sse_decode_cell_value(SseDeserializer deserializer);

  @protected
  ColumnDef sse_decode_column_def(SseDeserializer deserializer);

  @protected
  ColumnKind sse_decode_column_kind(SseDeserializer deserializer);

  @protected
  ColumnLayout sse_decode_column_layout(SseDeserializer deserializer);

  @protected
  ColumnMeta sse_decode_column_meta(SseDeserializer deserializer);

  @protected
  Completion sse_decode_completion(SseDeserializer deserializer);

  @protected
  CompletionItem sse_decode_completion_item(SseDeserializer deserializer);

  @protected
  CompletionKind sse_decode_completion_kind(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_connection_config(SseDeserializer deserializer);

  @protected
  DefaultValue sse_decode_default_value(SseDeserializer deserializer);

  @protected
  EditTarget sse_decode_edit_target(SseDeserializer deserializer);

  @protected
  Editability sse_decode_editability(SseDeserializer deserializer);

  @protected
  ExportEncoding sse_decode_export_encoding(SseDeserializer deserializer);

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  ExportOptions sse_decode_export_options(SseDeserializer deserializer);

  @protected
  ExportSummary sse_decode_export_summary(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Favorite sse_decode_favorite(SseDeserializer deserializer);

  @protected
  FilterCondition sse_decode_filter_condition(SseDeserializer deserializer);

  @protected
  FilterOp sse_decode_filter_op(SseDeserializer deserializer);

  @protected
  ForeignKeyDef sse_decode_foreign_key_def(SseDeserializer deserializer);

  @protected
  HistoryEntry sse_decode_history_entry(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  IndexDef sse_decode_index_def(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CellValue> sse_decode_list_cell_value(SseDeserializer deserializer);

  @protected
  List<ColumnDef> sse_decode_list_column_def(SseDeserializer deserializer);

  @protected
  List<ColumnLayout> sse_decode_list_column_layout(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnMeta> sse_decode_list_column_meta(SseDeserializer deserializer);

  @protected
  List<CompletionItem> sse_decode_list_completion_item(
    SseDeserializer deserializer,
  );

  @protected
  List<Favorite> sse_decode_list_favorite(SseDeserializer deserializer);

  @protected
  List<FilterCondition> sse_decode_list_filter_condition(
    SseDeserializer deserializer,
  );

  @protected
  List<ForeignKeyDef> sse_decode_list_foreign_key_def(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryEntry> sse_decode_list_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<IndexDef> sse_decode_list_index_def(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<List<CellValue>> sse_decode_list_list_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  List<CellValue?> sse_decode_list_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<SavedConnection> sse_decode_list_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  List<SqlToken> sse_decode_list_sql_token(SseDeserializer deserializer);

  @protected
  List<TableInfo> sse_decode_list_table_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CellValue? sse_decode_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  QuerySummary sse_decode_query_summary(SseDeserializer deserializer);

  @protected
  SavedConnection sse_decode_saved_connection(SseDeserializer deserializer);

  @protected
  SqlToken sse_decode_sql_token(SseDeserializer deserializer);

  @protected
  SqlTokenKind sse_decode_sql_token_kind(SseDeserializer deserializer);

  @protected
  TableInfo sse_decode_table_info(SseDeserializer deserializer);

  @protected
  TableStructure sse_decode_table_structure(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cell_value(
    CellValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_target(
    EditTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_options(
    ExportOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_cell_value(CellValue self, SseSerializer serializer);

  @protected
  void sse_encode_column_def(ColumnDef self, SseSerializer serializer);

  @protected
  void sse_encode_column_kind(ColumnKind self, SseSerializer serializer);

  @protected
  void sse_encode_column_layout(ColumnLayout self, SseSerializer serializer);

  @protected
  void sse_encode_column_meta(ColumnMeta self, SseSerializer serializer);

  @protected
  void sse_encode_completion(Completion self, SseSerializer serializer);

  @protected
  void sse_encode_completion_item(
    CompletionItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_completion_kind(
    CompletionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_default_value(DefaultValue self, SseSerializer serializer);

  @protected
  void sse_encode_edit_target(EditTarget self, SseSerializer serializer);

  @protected
  void sse_encode_editability(Editability self, SseSerializer serializer);

  @protected
  void sse_encode_export_encoding(
    ExportEncoding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_export_options(ExportOptions self, SseSerializer serializer);

  @protected
  void sse_encode_export_summary(ExportSummary self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_favorite(Favorite self, SseSerializer serializer);

  @protected
  void sse_encode_filter_condition(
    FilterCondition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_filter_op(FilterOp self, SseSerializer serializer);

  @protected
  void sse_encode_foreign_key_def(ForeignKeyDef self, SseSerializer serializer);

  @protected
  void sse_encode_history_entry(HistoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_index_def(IndexDef self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell_value(
    List<CellValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_def(
    List<ColumnDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_layout(
    List<ColumnLayout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_meta(
    List<ColumnMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_completion_item(
    List<CompletionItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_favorite(List<Favorite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_filter_condition(
    List<FilterCondition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_foreign_key_def(
    List<ForeignKeyDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_entry(
    List<HistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_index_def(List<IndexDef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_cell_value(
    List<List<CellValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_cell_value(
    List<CellValue?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_connection(
    List<SavedConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sql_token(List<SqlToken> self, SseSerializer serializer);

  @protected
  void sse_encode_list_table_info(
    List<TableInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cell_value(
    CellValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_query_summary(QuerySummary self, SseSerializer serializer);

  @protected
  void sse_encode_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sql_token(SqlToken self, SseSerializer serializer);

  @protected
  void sse_encode_sql_token_kind(SqlTokenKind self, SseSerializer serializer);

  @protected
  void sse_encode_table_info(TableInfo self, SseSerializer serializer);

  @protected
  void sse_encode_table_structure(
    TableStructure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
