// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/connections.dart';
import 'api/csv_import.dart';
import 'api/db.dart';
import 'api/editor.dart';
import 'api/layouts.dart';
import 'api/options.dart';
import 'api/preferences.dart';
import 'api/schema.dart';
import 'api/value.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlterPlan dco_decode_alter_plan(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CellValue dco_decode_box_autoadd_cell_value(dynamic raw);

  @protected
  ConnectionConfig dco_decode_box_autoadd_connection_config(dynamic raw);

  @protected
  EditTarget dco_decode_box_autoadd_edit_target(dynamic raw);

  @protected
  ExportOptions dco_decode_box_autoadd_export_options(dynamic raw);

  @protected
  HostKeyIssue dco_decode_box_autoadd_host_key_issue(dynamic raw);

  @protected
  ImportOptions dco_decode_box_autoadd_import_options(dynamic raw);

  @protected
  ImportProgress dco_decode_box_autoadd_import_progress(dynamic raw);

  @protected
  ImportReport dco_decode_box_autoadd_import_report(dynamic raw);

  @protected
  ImportRequest dco_decode_box_autoadd_import_request(dynamic raw);

  @protected
  Preferences dco_decode_box_autoadd_preferences(dynamic raw);

  @protected
  QuerySummary dco_decode_box_autoadd_query_summary(dynamic raw);

  @protected
  SavedConnection dco_decode_box_autoadd_saved_connection(dynamic raw);

  @protected
  SshHop dco_decode_box_autoadd_ssh_hop(dynamic raw);

  @protected
  StatementFailure dco_decode_box_autoadd_statement_failure(dynamic raw);

  @protected
  TableDraft dco_decode_box_autoadd_table_draft(dynamic raw);

  @protected
  TableStructure dco_decode_box_autoadd_table_structure(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CellValue dco_decode_cell_value(dynamic raw);

  @protected
  ColumnDef dco_decode_column_def(dynamic raw);

  @protected
  ColumnDraft dco_decode_column_draft(dynamic raw);

  @protected
  ColumnKind dco_decode_column_kind(dynamic raw);

  @protected
  ColumnLayout dco_decode_column_layout(dynamic raw);

  @protected
  ColumnMeta dco_decode_column_meta(dynamic raw);

  @protected
  Completion dco_decode_completion(dynamic raw);

  @protected
  CompletionItem dco_decode_completion_item(dynamic raw);

  @protected
  CompletionKind dco_decode_completion_kind(dynamic raw);

  @protected
  ConnectionConfig dco_decode_connection_config(dynamic raw);

  @protected
  ConnectionOptions dco_decode_connection_options(dynamic raw);

  @protected
  CsvPreview dco_decode_csv_preview(dynamic raw);

  @protected
  DefaultValue dco_decode_default_value(dynamic raw);

  @protected
  DisplayCell dco_decode_display_cell(dynamic raw);

  @protected
  EditTarget dco_decode_edit_target(dynamic raw);

  @protected
  Editability dco_decode_editability(dynamic raw);

  @protected
  ExportEncoding dco_decode_export_encoding(dynamic raw);

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  ExportOptions dco_decode_export_options(dynamic raw);

  @protected
  ExportSummary dco_decode_export_summary(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Favorite dco_decode_favorite(dynamic raw);

  @protected
  FilterCondition dco_decode_filter_condition(dynamic raw);

  @protected
  FilterOp dco_decode_filter_op(dynamic raw);

  @protected
  ForeignKeyDef dco_decode_foreign_key_def(dynamic raw);

  @protected
  ForeignKeyDraft dco_decode_foreign_key_draft(dynamic raw);

  @protected
  HistoryEntry dco_decode_history_entry(dynamic raw);

  @protected
  HostKeyIssue dco_decode_host_key_issue(dynamic raw);

  @protected
  HostKeyIssueKind dco_decode_host_key_issue_kind(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImportOptions dco_decode_import_options(dynamic raw);

  @protected
  ImportOutcome dco_decode_import_outcome(dynamic raw);

  @protected
  ImportProgress dco_decode_import_progress(dynamic raw);

  @protected
  ImportReport dco_decode_import_report(dynamic raw);

  @protected
  ImportRequest dco_decode_import_request(dynamic raw);

  @protected
  ImportStatus dco_decode_import_status(dynamic raw);

  @protected
  ImportTarget dco_decode_import_target(dynamic raw);

  @protected
  IndexDef dco_decode_index_def(dynamic raw);

  @protected
  IndexDraft dco_decode_index_draft(dynamic raw);

  @protected
  IndexKind dco_decode_index_kind(dynamic raw);

  @protected
  IndexPart dco_decode_index_part(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CellValue> dco_decode_list_cell_value(dynamic raw);

  @protected
  List<ColumnDef> dco_decode_list_column_def(dynamic raw);

  @protected
  List<ColumnDraft> dco_decode_list_column_draft(dynamic raw);

  @protected
  List<ColumnLayout> dco_decode_list_column_layout(dynamic raw);

  @protected
  List<ColumnMeta> dco_decode_list_column_meta(dynamic raw);

  @protected
  List<CompletionItem> dco_decode_list_completion_item(dynamic raw);

  @protected
  List<DisplayCell> dco_decode_list_display_cell(dynamic raw);

  @protected
  List<Favorite> dco_decode_list_favorite(dynamic raw);

  @protected
  List<FilterCondition> dco_decode_list_filter_condition(dynamic raw);

  @protected
  List<ForeignKeyDef> dco_decode_list_foreign_key_def(dynamic raw);

  @protected
  List<ForeignKeyDraft> dco_decode_list_foreign_key_draft(dynamic raw);

  @protected
  List<HistoryEntry> dco_decode_list_history_entry(dynamic raw);

  @protected
  List<IndexDef> dco_decode_list_index_def(dynamic raw);

  @protected
  List<IndexDraft> dco_decode_list_index_draft(dynamic raw);

  @protected
  List<IndexPart> dco_decode_list_index_part(dynamic raw);

  @protected
  List<List<CellValue>> dco_decode_list_list_cell_value(dynamic raw);

  @protected
  List<List<DisplayCell>> dco_decode_list_list_display_cell(dynamic raw);

  @protected
  List<String?> dco_decode_list_opt_String(dynamic raw);

  @protected
  List<CellValue?> dco_decode_list_opt_box_autoadd_cell_value(dynamic raw);

  @protected
  List<int?> dco_decode_list_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<PreviewRow> dco_decode_list_preview_row(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<RowError> dco_decode_list_row_error(dynamic raw);

  @protected
  List<SavedConnection> dco_decode_list_saved_connection(dynamic raw);

  @protected
  List<SqlToken> dco_decode_list_sql_token(dynamic raw);

  @protected
  List<SshHop> dco_decode_list_ssh_hop(dynamic raw);

  @protected
  List<StatementOutcome> dco_decode_list_statement_outcome(dynamic raw);

  @protected
  List<TableInfo> dco_decode_list_table_info(dynamic raw);

  @protected
  List<TargetColumn> dco_decode_list_target_column(dynamic raw);

  @protected
  OnError dco_decode_on_error(dynamic raw);

  @protected
  OpenSessionError dco_decode_open_session_error(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CellValue? dco_decode_opt_box_autoadd_cell_value(dynamic raw);

  @protected
  HostKeyIssue? dco_decode_opt_box_autoadd_host_key_issue(dynamic raw);

  @protected
  QuerySummary? dco_decode_opt_box_autoadd_query_summary(dynamic raw);

  @protected
  StatementFailure? dco_decode_opt_box_autoadd_statement_failure(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Preferences dco_decode_preferences(dynamic raw);

  @protected
  PreviewRow dco_decode_preview_row(dynamic raw);

  @protected
  QuerySummary dco_decode_query_summary(dynamic raw);

  @protected
  RowError dco_decode_row_error(dynamic raw);

  @protected
  SavedConnection dco_decode_saved_connection(dynamic raw);

  @protected
  ScriptSummary dco_decode_script_summary(dynamic raw);

  @protected
  SqlToken dco_decode_sql_token(dynamic raw);

  @protected
  SqlTokenKind dco_decode_sql_token_kind(dynamic raw);

  @protected
  SshAuth dco_decode_ssh_auth(dynamic raw);

  @protected
  SshHop dco_decode_ssh_hop(dynamic raw);

  @protected
  SshOptions dco_decode_ssh_options(dynamic raw);

  @protected
  SslMode dco_decode_ssl_mode(dynamic raw);

  @protected
  SslOptions dco_decode_ssl_options(dynamic raw);

  @protected
  StatementFailure dco_decode_statement_failure(dynamic raw);

  @protected
  StatementOutcome dco_decode_statement_outcome(dynamic raw);

  @protected
  TableDraft dco_decode_table_draft(dynamic raw);

  @protected
  TableInfo dco_decode_table_info(dynamic raw);

  @protected
  TableStructure dco_decode_table_structure(dynamic raw);

  @protected
  TargetColumn dco_decode_target_column(dynamic raw);

  @protected
  ThemeMode dco_decode_theme_mode(dynamic raw);

  @protected
  TimeoutOptions dco_decode_timeout_options(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlterPlan sse_decode_alter_plan(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CellValue sse_decode_box_autoadd_cell_value(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_box_autoadd_connection_config(
    SseDeserializer deserializer,
  );

  @protected
  EditTarget sse_decode_box_autoadd_edit_target(SseDeserializer deserializer);

  @protected
  ExportOptions sse_decode_box_autoadd_export_options(
    SseDeserializer deserializer,
  );

  @protected
  HostKeyIssue sse_decode_box_autoadd_host_key_issue(
    SseDeserializer deserializer,
  );

  @protected
  ImportOptions sse_decode_box_autoadd_import_options(
    SseDeserializer deserializer,
  );

  @protected
  ImportProgress sse_decode_box_autoadd_import_progress(
    SseDeserializer deserializer,
  );

  @protected
  ImportReport sse_decode_box_autoadd_import_report(
    SseDeserializer deserializer,
  );

  @protected
  ImportRequest sse_decode_box_autoadd_import_request(
    SseDeserializer deserializer,
  );

  @protected
  Preferences sse_decode_box_autoadd_preferences(SseDeserializer deserializer);

  @protected
  QuerySummary sse_decode_box_autoadd_query_summary(
    SseDeserializer deserializer,
  );

  @protected
  SavedConnection sse_decode_box_autoadd_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  SshHop sse_decode_box_autoadd_ssh_hop(SseDeserializer deserializer);

  @protected
  StatementFailure sse_decode_box_autoadd_statement_failure(
    SseDeserializer deserializer,
  );

  @protected
  TableDraft sse_decode_box_autoadd_table_draft(SseDeserializer deserializer);

  @protected
  TableStructure sse_decode_box_autoadd_table_structure(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CellValue sse_decode_cell_value(SseDeserializer deserializer);

  @protected
  ColumnDef sse_decode_column_def(SseDeserializer deserializer);

  @protected
  ColumnDraft sse_decode_column_draft(SseDeserializer deserializer);

  @protected
  ColumnKind sse_decode_column_kind(SseDeserializer deserializer);

  @protected
  ColumnLayout sse_decode_column_layout(SseDeserializer deserializer);

  @protected
  ColumnMeta sse_decode_column_meta(SseDeserializer deserializer);

  @protected
  Completion sse_decode_completion(SseDeserializer deserializer);

  @protected
  CompletionItem sse_decode_completion_item(SseDeserializer deserializer);

  @protected
  CompletionKind sse_decode_completion_kind(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_connection_config(SseDeserializer deserializer);

  @protected
  ConnectionOptions sse_decode_connection_options(SseDeserializer deserializer);

  @protected
  CsvPreview sse_decode_csv_preview(SseDeserializer deserializer);

  @protected
  DefaultValue sse_decode_default_value(SseDeserializer deserializer);

  @protected
  DisplayCell sse_decode_display_cell(SseDeserializer deserializer);

  @protected
  EditTarget sse_decode_edit_target(SseDeserializer deserializer);

  @protected
  Editability sse_decode_editability(SseDeserializer deserializer);

  @protected
  ExportEncoding sse_decode_export_encoding(SseDeserializer deserializer);

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  ExportOptions sse_decode_export_options(SseDeserializer deserializer);

  @protected
  ExportSummary sse_decode_export_summary(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Favorite sse_decode_favorite(SseDeserializer deserializer);

  @protected
  FilterCondition sse_decode_filter_condition(SseDeserializer deserializer);

  @protected
  FilterOp sse_decode_filter_op(SseDeserializer deserializer);

  @protected
  ForeignKeyDef sse_decode_foreign_key_def(SseDeserializer deserializer);

  @protected
  ForeignKeyDraft sse_decode_foreign_key_draft(SseDeserializer deserializer);

  @protected
  HistoryEntry sse_decode_history_entry(SseDeserializer deserializer);

  @protected
  HostKeyIssue sse_decode_host_key_issue(SseDeserializer deserializer);

  @protected
  HostKeyIssueKind sse_decode_host_key_issue_kind(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImportOptions sse_decode_import_options(SseDeserializer deserializer);

  @protected
  ImportOutcome sse_decode_import_outcome(SseDeserializer deserializer);

  @protected
  ImportProgress sse_decode_import_progress(SseDeserializer deserializer);

  @protected
  ImportReport sse_decode_import_report(SseDeserializer deserializer);

  @protected
  ImportRequest sse_decode_import_request(SseDeserializer deserializer);

  @protected
  ImportStatus sse_decode_import_status(SseDeserializer deserializer);

  @protected
  ImportTarget sse_decode_import_target(SseDeserializer deserializer);

  @protected
  IndexDef sse_decode_index_def(SseDeserializer deserializer);

  @protected
  IndexDraft sse_decode_index_draft(SseDeserializer deserializer);

  @protected
  IndexKind sse_decode_index_kind(SseDeserializer deserializer);

  @protected
  IndexPart sse_decode_index_part(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CellValue> sse_decode_list_cell_value(SseDeserializer deserializer);

  @protected
  List<ColumnDef> sse_decode_list_column_def(SseDeserializer deserializer);

  @protected
  List<ColumnDraft> sse_decode_list_column_draft(SseDeserializer deserializer);

  @protected
  List<ColumnLayout> sse_decode_list_column_layout(
    SseDeserializer deserializer,
  );

  @protected
  List<ColumnMeta> sse_decode_list_column_meta(SseDeserializer deserializer);

  @protected
  List<CompletionItem> sse_decode_list_completion_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DisplayCell> sse_decode_list_display_cell(SseDeserializer deserializer);

  @protected
  List<Favorite> sse_decode_list_favorite(SseDeserializer deserializer);

  @protected
  List<FilterCondition> sse_decode_list_filter_condition(
    SseDeserializer deserializer,
  );

  @protected
  List<ForeignKeyDef> sse_decode_list_foreign_key_def(
    SseDeserializer deserializer,
  );

  @protected
  List<ForeignKeyDraft> sse_decode_list_foreign_key_draft(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryEntry> sse_decode_list_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<IndexDef> sse_decode_list_index_def(SseDeserializer deserializer);

  @protected
  List<IndexDraft> sse_decode_list_index_draft(SseDeserializer deserializer);

  @protected
  List<IndexPart> sse_decode_list_index_part(SseDeserializer deserializer);

  @protected
  List<List<CellValue>> sse_decode_list_list_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  List<List<DisplayCell>> sse_decode_list_list_display_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<String?> sse_decode_list_opt_String(SseDeserializer deserializer);

  @protected
  List<CellValue?> sse_decode_list_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  List<int?> sse_decode_list_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<PreviewRow> sse_decode_list_preview_row(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<RowError> sse_decode_list_row_error(SseDeserializer deserializer);

  @protected
  List<SavedConnection> sse_decode_list_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  List<SqlToken> sse_decode_list_sql_token(SseDeserializer deserializer);

  @protected
  List<SshHop> sse_decode_list_ssh_hop(SseDeserializer deserializer);

  @protected
  List<StatementOutcome> sse_decode_list_statement_outcome(
    SseDeserializer deserializer,
  );

  @protected
  List<TableInfo> sse_decode_list_table_info(SseDeserializer deserializer);

  @protected
  List<TargetColumn> sse_decode_list_target_column(
    SseDeserializer deserializer,
  );

  @protected
  OnError sse_decode_on_error(SseDeserializer deserializer);

  @protected
  OpenSessionError sse_decode_open_session_error(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CellValue? sse_decode_opt_box_autoadd_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  HostKeyIssue? sse_decode_opt_box_autoadd_host_key_issue(
    SseDeserializer deserializer,
  );

  @protected
  QuerySummary? sse_decode_opt_box_autoadd_query_summary(
    SseDeserializer deserializer,
  );

  @protected
  StatementFailure? sse_decode_opt_box_autoadd_statement_failure(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Preferences sse_decode_preferences(SseDeserializer deserializer);

  @protected
  PreviewRow sse_decode_preview_row(SseDeserializer deserializer);

  @protected
  QuerySummary sse_decode_query_summary(SseDeserializer deserializer);

  @protected
  RowError sse_decode_row_error(SseDeserializer deserializer);

  @protected
  SavedConnection sse_decode_saved_connection(SseDeserializer deserializer);

  @protected
  ScriptSummary sse_decode_script_summary(SseDeserializer deserializer);

  @protected
  SqlToken sse_decode_sql_token(SseDeserializer deserializer);

  @protected
  SqlTokenKind sse_decode_sql_token_kind(SseDeserializer deserializer);

  @protected
  SshAuth sse_decode_ssh_auth(SseDeserializer deserializer);

  @protected
  SshHop sse_decode_ssh_hop(SseDeserializer deserializer);

  @protected
  SshOptions sse_decode_ssh_options(SseDeserializer deserializer);

  @protected
  SslMode sse_decode_ssl_mode(SseDeserializer deserializer);

  @protected
  SslOptions sse_decode_ssl_options(SseDeserializer deserializer);

  @protected
  StatementFailure sse_decode_statement_failure(SseDeserializer deserializer);

  @protected
  StatementOutcome sse_decode_statement_outcome(SseDeserializer deserializer);

  @protected
  TableDraft sse_decode_table_draft(SseDeserializer deserializer);

  @protected
  TableInfo sse_decode_table_info(SseDeserializer deserializer);

  @protected
  TableStructure sse_decode_table_structure(SseDeserializer deserializer);

  @protected
  TargetColumn sse_decode_target_column(SseDeserializer deserializer);

  @protected
  ThemeMode sse_decode_theme_mode(SseDeserializer deserializer);

  @protected
  TimeoutOptions sse_decode_timeout_options(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_alter_plan(AlterPlan self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cell_value(
    CellValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_target(
    EditTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_options(
    ExportOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_host_key_issue(
    HostKeyIssue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_options(
    ImportOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_progress(
    ImportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_report(
    ImportReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_import_request(
    ImportRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_preferences(
    Preferences self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_query_summary(
    QuerySummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ssh_hop(SshHop self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_statement_failure(
    StatementFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_table_draft(
    TableDraft self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_table_structure(
    TableStructure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_cell_value(CellValue self, SseSerializer serializer);

  @protected
  void sse_encode_column_def(ColumnDef self, SseSerializer serializer);

  @protected
  void sse_encode_column_draft(ColumnDraft self, SseSerializer serializer);

  @protected
  void sse_encode_column_kind(ColumnKind self, SseSerializer serializer);

  @protected
  void sse_encode_column_layout(ColumnLayout self, SseSerializer serializer);

  @protected
  void sse_encode_column_meta(ColumnMeta self, SseSerializer serializer);

  @protected
  void sse_encode_completion(Completion self, SseSerializer serializer);

  @protected
  void sse_encode_completion_item(
    CompletionItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_completion_kind(
    CompletionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_connection_options(
    ConnectionOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_csv_preview(CsvPreview self, SseSerializer serializer);

  @protected
  void sse_encode_default_value(DefaultValue self, SseSerializer serializer);

  @protected
  void sse_encode_display_cell(DisplayCell self, SseSerializer serializer);

  @protected
  void sse_encode_edit_target(EditTarget self, SseSerializer serializer);

  @protected
  void sse_encode_editability(Editability self, SseSerializer serializer);

  @protected
  void sse_encode_export_encoding(
    ExportEncoding self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_export_options(ExportOptions self, SseSerializer serializer);

  @protected
  void sse_encode_export_summary(ExportSummary self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_favorite(Favorite self, SseSerializer serializer);

  @protected
  void sse_encode_filter_condition(
    FilterCondition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_filter_op(FilterOp self, SseSerializer serializer);

  @protected
  void sse_encode_foreign_key_def(ForeignKeyDef self, SseSerializer serializer);

  @protected
  void sse_encode_foreign_key_draft(
    ForeignKeyDraft self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_entry(HistoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_host_key_issue(HostKeyIssue self, SseSerializer serializer);

  @protected
  void sse_encode_host_key_issue_kind(
    HostKeyIssueKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_import_options(ImportOptions self, SseSerializer serializer);

  @protected
  void sse_encode_import_outcome(ImportOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_import_progress(
    ImportProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_import_report(ImportReport self, SseSerializer serializer);

  @protected
  void sse_encode_import_request(ImportRequest self, SseSerializer serializer);

  @protected
  void sse_encode_import_status(ImportStatus self, SseSerializer serializer);

  @protected
  void sse_encode_import_target(ImportTarget self, SseSerializer serializer);

  @protected
  void sse_encode_index_def(IndexDef self, SseSerializer serializer);

  @protected
  void sse_encode_index_draft(IndexDraft self, SseSerializer serializer);

  @protected
  void sse_encode_index_kind(IndexKind self, SseSerializer serializer);

  @protected
  void sse_encode_index_part(IndexPart self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell_value(
    List<CellValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_def(
    List<ColumnDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_draft(
    List<ColumnDraft> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_layout(
    List<ColumnLayout> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_meta(
    List<ColumnMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_completion_item(
    List<CompletionItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_display_cell(
    List<DisplayCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_favorite(List<Favorite> self, SseSerializer serializer);

  @protected
  void sse_encode_list_filter_condition(
    List<FilterCondition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_foreign_key_def(
    List<ForeignKeyDef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_foreign_key_draft(
    List<ForeignKeyDraft> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_entry(
    List<HistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_index_def(List<IndexDef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_index_draft(
    List<IndexDraft> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_index_part(
    List<IndexPart> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_cell_value(
    List<List<CellValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_display_cell(
    List<List<DisplayCell>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_String(List<String?> self, SseSerializer serializer);

  @protected
  void sse_encode_list_opt_box_autoadd_cell_value(
    List<CellValue?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_opt_box_autoadd_u_32(
    List<int?> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_preview_row(
    List<PreviewRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_row_error(List<RowError> self, SseSerializer serializer);

  @protected
  void sse_encode_list_saved_connection(
    List<SavedConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sql_token(List<SqlToken> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ssh_hop(List<SshHop> self, SseSerializer serializer);

  @protected
  void sse_encode_list_statement_outcome(
    List<StatementOutcome> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_info(
    List<TableInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_target_column(
    List<TargetColumn> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_on_error(OnError self, SseSerializer serializer);

  @protected
  void sse_encode_open_session_error(
    OpenSessionError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_cell_value(
    CellValue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_host_key_issue(
    HostKeyIssue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_query_summary(
    QuerySummary? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_statement_failure(
    StatementFailure? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_preferences(Preferences self, SseSerializer serializer);

  @protected
  void sse_encode_preview_row(PreviewRow self, SseSerializer serializer);

  @protected
  void sse_encode_query_summary(QuerySummary self, SseSerializer serializer);

  @protected
  void sse_encode_row_error(RowError self, SseSerializer serializer);

  @protected
  void sse_encode_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_script_summary(ScriptSummary self, SseSerializer serializer);

  @protected
  void sse_encode_sql_token(SqlToken self, SseSerializer serializer);

  @protected
  void sse_encode_sql_token_kind(SqlTokenKind self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_auth(SshAuth self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_hop(SshHop self, SseSerializer serializer);

  @protected
  void sse_encode_ssh_options(SshOptions self, SseSerializer serializer);

  @protected
  void sse_encode_ssl_mode(SslMode self, SseSerializer serializer);

  @protected
  void sse_encode_ssl_options(SslOptions self, SseSerializer serializer);

  @protected
  void sse_encode_statement_failure(
    StatementFailure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_statement_outcome(
    StatementOutcome self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_table_draft(TableDraft self, SseSerializer serializer);

  @protected
  void sse_encode_table_info(TableInfo self, SseSerializer serializer);

  @protected
  void sse_encode_table_structure(
    TableStructure self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_target_column(TargetColumn self, SseSerializer serializer);

  @protected
  void sse_encode_theme_mode(ThemeMode self, SseSerializer serializer);

  @protected
  void sse_encode_timeout_options(
    TimeoutOptions self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
