// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/connections.dart';
import 'api/db.dart';
import 'api/schema.dart';
import 'api/value.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CellValue dco_decode_box_autoadd_cell_value(dynamic raw);

  @protected
  ConnectionConfig dco_decode_box_autoadd_connection_config(dynamic raw);

  @protected
  EditTarget dco_decode_box_autoadd_edit_target(dynamic raw);

  @protected
  SavedConnection dco_decode_box_autoadd_saved_connection(dynamic raw);

  @protected
  CellValue dco_decode_cell_value(dynamic raw);

  @protected
  ColumnMeta dco_decode_column_meta(dynamic raw);

  @protected
  ConnectionConfig dco_decode_connection_config(dynamic raw);

  @protected
  EditTarget dco_decode_edit_target(dynamic raw);

  @protected
  Editability dco_decode_editability(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CellValue> dco_decode_list_cell_value(dynamic raw);

  @protected
  List<ColumnMeta> dco_decode_list_column_meta(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<List<CellValue>> dco_decode_list_list_cell_value(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_usize_strict(dynamic raw);

  @protected
  List<SavedConnection> dco_decode_list_saved_connection(dynamic raw);

  @protected
  List<TableInfo> dco_decode_list_table_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  QuerySummary dco_decode_query_summary(dynamic raw);

  @protected
  SavedConnection dco_decode_saved_connection(dynamic raw);

  @protected
  TableInfo dco_decode_table_info(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CellValue sse_decode_box_autoadd_cell_value(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_box_autoadd_connection_config(
    SseDeserializer deserializer,
  );

  @protected
  EditTarget sse_decode_box_autoadd_edit_target(SseDeserializer deserializer);

  @protected
  SavedConnection sse_decode_box_autoadd_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  CellValue sse_decode_cell_value(SseDeserializer deserializer);

  @protected
  ColumnMeta sse_decode_column_meta(SseDeserializer deserializer);

  @protected
  ConnectionConfig sse_decode_connection_config(SseDeserializer deserializer);

  @protected
  EditTarget sse_decode_edit_target(SseDeserializer deserializer);

  @protected
  Editability sse_decode_editability(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CellValue> sse_decode_list_cell_value(SseDeserializer deserializer);

  @protected
  List<ColumnMeta> sse_decode_list_column_meta(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<List<CellValue>> sse_decode_list_list_cell_value(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_usize_strict(SseDeserializer deserializer);

  @protected
  List<SavedConnection> sse_decode_list_saved_connection(
    SseDeserializer deserializer,
  );

  @protected
  List<TableInfo> sse_decode_list_table_info(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  QuerySummary sse_decode_query_summary(SseDeserializer deserializer);

  @protected
  SavedConnection sse_decode_saved_connection(SseDeserializer deserializer);

  @protected
  TableInfo sse_decode_table_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_cell_value(
    CellValue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_edit_target(
    EditTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_cell_value(CellValue self, SseSerializer serializer);

  @protected
  void sse_encode_column_meta(ColumnMeta self, SseSerializer serializer);

  @protected
  void sse_encode_connection_config(
    ConnectionConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_edit_target(EditTarget self, SseSerializer serializer);

  @protected
  void sse_encode_editability(Editability self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cell_value(
    List<CellValue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_column_meta(
    List<ColumnMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_cell_value(
    List<List<CellValue>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_usize_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_saved_connection(
    List<SavedConnection> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_table_info(
    List<TableInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_query_summary(QuerySummary self, SseSerializer serializer);

  @protected
  void sse_encode_saved_connection(
    SavedConnection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_table_info(TableInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
